/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\box.o c:\users\john\documents\nim\bomberman\nimcache\box.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct Box140009 Box140009;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(NIM_BOOL, checkcollision_140017)(Box140009* a, Box140009* b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_17042;
TNimType NTI140009; /* Box */
extern TNimType NTI114; /* int32 */

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NIM_BOOL, checkcollision_140017)(Box140009* a, Box140009* b) {
	NIM_BOOL result;
	nimfr("checkCollision", "box.nim")
{	result = 0;
	nimln(6, "box.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		NI32 TMP298;
		NI32 TMP299;
		NI32 TMP300;
		NI32 TMP301;
		nimln(8, "box.nim");
		LOC3 = 0;
		nimln(7, "box.nim");
		LOC4 = 0;
		nimln(6, "box.nim");
		LOC5 = 0;
		TMP298 = addInt((*a).Field0, (*a).Field2);
		LOC5 = ((NI32)(TMP298) < (*b).Field0);
		if (LOC5) goto LA6;
		nimln(7, "box.nim");
		TMP299 = addInt((*b).Field0, (*b).Field2);
		LOC5 = ((NI32)(TMP299) < (*a).Field0);
		LA6: ;
		LOC4 = LOC5;
		if (LOC4) goto LA7;
		nimln(8, "box.nim");
		TMP300 = addInt((*a).Field1, (*a).Field3);
		LOC4 = ((NI32)(TMP300) < (*b).Field1);
		LA7: ;
		LOC3 = LOC4;
		if (LOC3) goto LA8;
		nimln(9, "box.nim");
		TMP301 = addInt((*b).Field1, (*b).Field3);
		LOC3 = ((NI32)(TMP301) < (*a).Field1);
		LA8: ;
		if (!LOC3) goto LA9;
		nimln(10, "box.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	nimln(12, "box.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_boxInit)(void) {
	nimfr("box", "box.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_boxDatInit)(void) {
static TNimNode* TMP303[4];
static TNimNode TMP296[5];
NTI140009.size = sizeof(Box140009);
NTI140009.kind = 18;
NTI140009.base = 0;
NTI140009.flags = 3;
TMP303[0] = &TMP296[1];
TMP296[1].kind = 1;
TMP296[1].offset = offsetof(Box140009, Field0);
TMP296[1].typ = (&NTI114);
TMP296[1].name = "Field0";
TMP303[1] = &TMP296[2];
TMP296[2].kind = 1;
TMP296[2].offset = offsetof(Box140009, Field1);
TMP296[2].typ = (&NTI114);
TMP296[2].name = "Field1";
TMP303[2] = &TMP296[3];
TMP296[3].kind = 1;
TMP296[3].offset = offsetof(Box140009, Field2);
TMP296[3].typ = (&NTI114);
TMP296[3].name = "Field2";
TMP303[3] = &TMP296[4];
TMP296[4].kind = 1;
TMP296[4].offset = offsetof(Box140009, Field3);
TMP296[4].typ = (&NTI114);
TMP296[4].name = "Field3";
TMP296[0].len = 4; TMP296[0].kind = 2; TMP296[0].sons = &TMP303[0];
NTI140009.node = &TMP296[0];
}

