/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\sdl_game_notopengl\nimcache\collisionbox.o c:\users\john\documents\nim\sdl_game_notopengl\nimcache\collisionbox.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct Box123014 Box123014;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct Box123014 {
NI Field0;
NI Field1;
NI Field2;
NI Field3;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
NI kf_123009;
TNimType NTI123014; /* Box */
extern TNimType NTI108; /* int */
extern TFrame* frameptr_17042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_collisionboxInit)(void) {
	nimfr("collisionbox", "collisionbox.nim")
	nimln(1, "collisionbox.nim");
	kf_123009 = ((NI) 534);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_collisionboxDatInit)(void) {
static TNimNode* TMP164[4];
static TNimNode TMP161[5];
NTI123014.size = sizeof(Box123014);
NTI123014.kind = 18;
NTI123014.base = 0;
NTI123014.flags = 3;
TMP164[0] = &TMP161[1];
TMP161[1].kind = 1;
TMP161[1].offset = offsetof(Box123014, Field0);
TMP161[1].typ = (&NTI108);
TMP161[1].name = "Field0";
TMP164[1] = &TMP161[2];
TMP161[2].kind = 1;
TMP161[2].offset = offsetof(Box123014, Field1);
TMP161[2].typ = (&NTI108);
TMP161[2].name = "Field1";
TMP164[2] = &TMP161[3];
TMP161[3].kind = 1;
TMP161[3].offset = offsetof(Box123014, Field2);
TMP161[3].typ = (&NTI108);
TMP161[3].name = "Field2";
TMP164[3] = &TMP161[4];
TMP161[4].kind = 1;
TMP161[4].offset = offsetof(Box123014, Field3);
TMP161[4].typ = (&NTI108);
TMP161[4].name = "Field3";
TMP161[0].len = 4; TMP161[0].kind = 2; TMP161[0].sons = &TMP164[0];
NTI123014.node = &TMP161[0];
}

