/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\engine.o c:\users\john\documents\nim\bomberman\nimcache\engine.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdio.h>
typedef struct WindowptrHEX3Aobjecttype121574 WindowptrHEX3Aobjecttype121574;
typedef struct RendererptrHEX3Aobjecttype121576 RendererptrHEX3Aobjecttype121576;
typedef struct TextureptrHEX3Aobjecttype121578 TextureptrHEX3Aobjecttype121578;
typedef struct TY142011 TY142011;
typedef struct Box140009 Box140009;
typedef struct TGenericSeq TGenericSeq;
typedef struct FontptrHEX3Aobjecttype137409 FontptrHEX3Aobjecttype137409;
typedef struct TY142015 TY142015;
typedef struct Color122280 Color122280;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct NimStringDesc NimStringDesc;
typedef struct SpriteHEX3Aobjecttype141009 SpriteHEX3Aobjecttype141009;
typedef struct Surface122290 Surface122290;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
typedef struct Pixelformat122284 Pixelformat122284;
typedef struct BlitmapptrHEX3Aobjecttype122332 BlitmapptrHEX3Aobjecttype122332;
typedef struct Palette122282 Palette122282;
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct Color122280 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(WindowptrHEX3Aobjecttype121574*, TY132189) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(RendererptrHEX3Aobjecttype121576*, TY131349) (WindowptrHEX3Aobjecttype121574* window, int index, int flags);
typedef N_CDECL_PTR(TextureptrHEX3Aobjecttype121578*, TY135643) (RendererptrHEX3Aobjecttype121576* renderer, NCSTRING file);
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef N_CDECL_PTR(int, TY135611) (int flags);
typedef N_CDECL_PTR(NCSTRING, TY132713) (void);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, TY137624) (void);
typedef N_CDECL_PTR(FontptrHEX3Aobjecttype137409*, TY137629) (NCSTRING file, int ptsize);
typedef N_CDECL_PTR(NI32, TY131623) (RendererptrHEX3Aobjecttype121576* renderer, TextureptrHEX3Aobjecttype121578* texture, Box140009* srcrect, Box140009* dstrect);
typedef N_CDECL_PTR(NI32, TY131033) (RendererptrHEX3Aobjecttype121576* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY131661) (RendererptrHEX3Aobjecttype121576* renderer);
typedef N_CDECL_PTR(void, TY131678) (RendererptrHEX3Aobjecttype121576* renderer);
typedef N_CDECL_PTR(Surface122290*, TY137835) (FontptrHEX3Aobjecttype137409* font, NCSTRING text, Color122280 fg);
typedef N_CDECL_PTR(TextureptrHEX3Aobjecttype121578*, TY131386) (RendererptrHEX3Aobjecttype121576* renderer, Surface122290* surface);
typedef N_CDECL_PTR(NI32, TY131404) (TextureptrHEX3Aobjecttype121578* texture, NU32* format, int* access, int* w, int* h);
typedef N_CDECL_PTR(void, TY131726) (Surface122290* surface);
typedef N_CDECL_PTR(void, TY131069) (TextureptrHEX3Aobjecttype121578* texture);
struct  WindowptrHEX3Aobjecttype121574  {
char dummy;
};
struct  RendererptrHEX3Aobjecttype121576  {
char dummy;
};
struct  TextureptrHEX3Aobjecttype121578  {
char dummy;
};
struct  FontptrHEX3Aobjecttype137409  {
char dummy;
};
typedef NI TY27820[16];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  SpriteHEX3Aobjecttype141009  {
Box140009 box;
NU8 spritetype;
};
struct  Surface122290  {
NU32 flags;
Pixelformat122284* format;
NI32 w;
NI32 h;
NI32 pitch;
void* pixels;
void* userdata;
NI32 locked;
void* lockdata;
Box140009 cliprect;
BlitmapptrHEX3Aobjecttype122332* map;
int refcount;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
typedef NU8 TY122314[2];
struct  Pixelformat122284  {
NU32 format;
Palette122282* palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY122314 padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
Pixelformat122284* next;
};
struct  BlitmapptrHEX3Aobjecttype122332  {
char dummy;
};
struct  Palette122282  {
int ncolors;
Color122280* colors;
NU32 version;
int refcount;
};
struct TY142011 {
  TGenericSeq Sup;
  Box140009 data[SEQ_DECL_SIZE];
};
struct TY142015 {
  TGenericSeq Sup;
  Color122280 data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY142011*, newseq_142034)(NI len);
N_NIMCALL(void, TMP310)(void* p, NI op);
N_NIMCALL(void, initengine_142030)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, TMP319)(void* p, NI op);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, drawsprite_142207)(SpriteHEX3Aobjecttype141009* sprite);
N_NIMCALL(NU8, getspritetype_141084)(SpriteHEX3Aobjecttype141009* obj);
N_NIMCALL(Box140009*, getbox_141072)(SpriteHEX3Aobjecttype141009* obj);
static N_INLINE(RendererptrHEX3Aobjecttype121576*, getrenderer_142225)(void);
static N_INLINE(WindowptrHEX3Aobjecttype121574*, getwindow_142234)(void);
static N_INLINE(TextureptrHEX3Aobjecttype121578*, getspritemap_142243)(void);
N_NIMCALL(void, clear_142252)(void);
N_NIMCALL(void, present_142261)(void);
N_NIMCALL(NI, getscreenwidth_142269)(void);
N_NIMCALL(NI, getscreenheight_142278)(void);
N_NIMCALL(void, rendertext_142287)(NCSTRING textstring, NI32 x, NI32 y, NU8 color);
static N_INLINE(void, destroy_133201)(Surface122290* surface);
STRING_LITERAL(TMP317, "Error, can\'t open font in engine.nim", 36);
NIM_CONST Box140009 TMP320 = {((int) 0),
((int) 0),
((int) 128),
((int) 128)}
;
NIM_CONST Box140009 TMP321 = {((int) 128),
((int) 0),
((int) 128),
((int) 128)}
;
NIM_CONST Box140009 TMP322 = {((int) 256),
((int) 0),
((int) 128),
((int) 128)}
;
NIM_CONST Box140009 TMP323 = {((int) 384),
((int) 0),
((int) 128),
((int) 128)}
;
NI32 screenwidth_142005;
NI32 screenheight_142007;
WindowptrHEX3Aobjecttype121574* window_142008;
RendererptrHEX3Aobjecttype121576* renderer_142009;
TextureptrHEX3Aobjecttype121578* spritemap_142010;
TY142011* spritepositions_142012;
FontptrHEX3Aobjecttype137409* font_142013;
TextureptrHEX3Aobjecttype121578* text_142014;
TY142015* fontcolor_142017;
extern TNimType NTI140009; /* Box */
TNimType NTI142011; /* seq[Rect] */
extern TY132189 Dl_132188;
extern TY131349 Dl_131348;
extern TY135643 Dl_135642;
extern TFrame* frameptr_17042;
extern Tgcheap48616 gch_48644;
extern TY135611 Dl_135610;
extern TY132713 Dl_132712;
extern TY137624 Dl_137623;
extern TY137629 Dl_137628;
extern TNimType NTI122280; /* Color */
TNimType NTI142015; /* seq[Color] */
extern TY131623 Dl_131622;
extern TY131033 Dl_131032;
extern TY131661 Dl_131660;
extern TY131678 Dl_131677;
extern TY137835 Dl_137834;
extern TY131386 Dl_131385;
extern TY131404 Dl_131403;
extern TY131726 Dl_131725;
extern TY131069 Dl_131068;
N_NIMCALL(void, TMP310)(void* p, NI op) {
	TY142011* a;
	NI LOC1;
	a = (TY142011*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NIMCALL(void, TMP319)(void* p, NI op) {
	TY142015* a;
	NI LOC1;
	a = (TY142015*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, initengine_142030)(void) {
	int err;
	NI32 sdlerr;
	Color122280 LOC17;
	Color122280 LOC18;
	Color122280 LOC19;
	nimfr("initEngine", "engine.nim")
	nimln(18, "engine.nim");
	window_142008 = Dl_132188("Nim tentative de jeu", ((int) 536805376), ((int) 536805376), screenwidth_142005, screenheight_142007, ((unsigned int) 4));
	nimln(20, "engine.nim");
	renderer_142009 = Dl_131348(window_142008, ((int) -1), ((NI32) 6));
	nimln(22, "engine.nim");
	spritemap_142010 = Dl_135642(renderer_142009, "test.png");
	nimln(23, "engine.nim");
	asgnRefNoCycle((void**) (&spritepositions_142012), newseq_142034(((NI) 5)));
	nimln(25, "engine.nim");
	err = Dl_135610(((int) 3));
	nimln(26, "engine.nim");
	{
		NCSTRING LOC5;
		NimStringDesc* LOC6;
		if (!(err == ((NI32) 0))) goto LA3;
		nimln(27, "engine.nim");
		LOC5 = 0;
		LOC5 = Dl_132712();
		LOC6 = 0;
		LOC6 = cstrToNimstr(LOC5);
		printf("%s\015\012", LOC6? (LOC6)->data:"nil");
	}
	LA3: ;
	nimln(29, "engine.nim");
	sdlerr = Dl_137623();
	nimln(30, "engine.nim");
	{
		NCSTRING LOC11;
		NimStringDesc* LOC12;
		if (!(sdlerr == ((NI32) -1))) goto LA9;
		nimln(31, "engine.nim");
		LOC11 = 0;
		LOC11 = Dl_132712();
		LOC12 = 0;
		LOC12 = cstrToNimstr(LOC11);
		printf("%s\015\012", LOC12? (LOC12)->data:"nil");
	}
	LA9: ;
	nimln(33, "engine.nim");
	font_142013 = Dl_137628("Hanken-Book.ttf", ((int) 20));
	nimln(34, "engine.nim");
	{
		if (!(font_142013 == NIM_NIL)) goto LA15;
		nimln(35, "engine.nim");
		printf("%s\015\012", ((NimStringDesc*) &TMP317)? (((NimStringDesc*) &TMP317))->data:"nil");
	}
	LA15: ;
	nimln(37, "engine.nim");
	if (fontcolor_142017) nimGCunrefNoCycle(fontcolor_142017);
	fontcolor_142017 = (TY142015*) newSeqRC1((&NTI142015), 0);
	nimln(38, "engine.nim");
	LOC17.Field0 = ((NU8) 0);
	LOC17.Field1 = ((NU8) 0);
	LOC17.Field2 = ((NU8) 0);
	LOC17.Field3 = ((NU8) 255);
	fontcolor_142017 = (TY142015*) incrSeq(&(fontcolor_142017)->Sup, sizeof(Color122280));
	fontcolor_142017->data[fontcolor_142017->Sup.len-1] = LOC17;
	nimln(39, "engine.nim");
	LOC18.Field0 = ((NU8) 122);
	LOC18.Field1 = ((NU8) 122);
	LOC18.Field2 = ((NU8) 122);
	LOC18.Field3 = ((NU8) 255);
	fontcolor_142017 = (TY142015*) incrSeq(&(fontcolor_142017)->Sup, sizeof(Color122280));
	fontcolor_142017->data[fontcolor_142017->Sup.len-1] = LOC18;
	nimln(40, "engine.nim");
	LOC19.Field0 = ((NU8) 255);
	LOC19.Field1 = ((NU8) 255);
	LOC19.Field2 = ((NU8) 255);
	LOC19.Field3 = ((NU8) 255);
	fontcolor_142017 = (TY142015*) incrSeq(&(fontcolor_142017)->Sup, sizeof(Color122280));
	fontcolor_142017->data[fontcolor_142017->Sup.len-1] = LOC19;
	nimln(42, "engine.nim");
	if ((NU)(((NI) 0)) >= (NU)(spritepositions_142012->Sup.len)) raiseIndexError();
	spritepositions_142012->data[((NI) 0)] = TMP320;
	nimln(43, "engine.nim");
	if ((NU)(((NI) 1)) >= (NU)(spritepositions_142012->Sup.len)) raiseIndexError();
	spritepositions_142012->data[((NI) 1)] = TMP321;
	nimln(44, "engine.nim");
	if ((NU)(((NI) 2)) >= (NU)(spritepositions_142012->Sup.len)) raiseIndexError();
	spritepositions_142012->data[((NI) 2)] = TMP322;
	nimln(45, "engine.nim");
	if ((NU)(((NI) 3)) >= (NU)(spritepositions_142012->Sup.len)) raiseIndexError();
	spritepositions_142012->data[((NI) 3)] = TMP323;
	popFrame();
}

N_NIMCALL(void, drawsprite_142207)(SpriteHEX3Aobjecttype141009* sprite) {
	NU8 LOC1;
	Box140009* LOC2;
	NI32 LOC3;
	nimfr("drawSprite", "engine.nim")
	nimln(48, "engine.nim");
	LOC1 = 0;
	LOC1 = getspritetype_141084(sprite);
	if ((NU)(LOC1) >= (NU)(spritepositions_142012->Sup.len)) raiseIndexError();
	LOC2 = 0;
	LOC2 = getbox_141072(sprite);
	LOC3 = 0;
	LOC3 = Dl_131622(renderer_142009, spritemap_142010, (&spritepositions_142012->data[LOC1]), LOC2);
	popFrame();
}

static N_INLINE(RendererptrHEX3Aobjecttype121576*, getrenderer_142225)(void) {
	RendererptrHEX3Aobjecttype121576* result;
	nimfr("getRenderer", "engine.nim")
	result = 0;
	nimln(51, "engine.nim");
	result = renderer_142009;
	popFrame();
	return result;
}

static N_INLINE(WindowptrHEX3Aobjecttype121574*, getwindow_142234)(void) {
	WindowptrHEX3Aobjecttype121574* result;
	nimfr("getWindow", "engine.nim")
	result = 0;
	nimln(54, "engine.nim");
	result = window_142008;
	popFrame();
	return result;
}

static N_INLINE(TextureptrHEX3Aobjecttype121578*, getspritemap_142243)(void) {
	TextureptrHEX3Aobjecttype121578* result;
	nimfr("getSpriteMap", "engine.nim")
	result = 0;
	nimln(57, "engine.nim");
	result = spritemap_142010;
	popFrame();
	return result;
}

N_NIMCALL(void, clear_142252)(void) {
	NI32 LOC1;
	int LOC2;
	nimfr("clear", "engine.nim")
	nimln(60, "engine.nim");
	LOC1 = 0;
	LOC1 = Dl_131032(renderer_142009, ((NU8) 30), ((NU8) 0), ((NU8) 0), ((NU8) 255));
	nimln(61, "engine.nim");
	LOC2 = 0;
	LOC2 = Dl_131660(renderer_142009);
	popFrame();
}

N_NIMCALL(void, present_142261)(void) {
	nimfr("present", "engine.nim")
	nimln(64, "engine.nim");
	Dl_131677(renderer_142009);
	popFrame();
}

N_NIMCALL(NI, getscreenwidth_142269)(void) {
	NI result;
	nimfr("getScreenWidth", "engine.nim")
	result = 0;
	nimln(67, "engine.nim");
	result = ((NI) (screenwidth_142005));
	popFrame();
	return result;
}

N_NIMCALL(NI, getscreenheight_142278)(void) {
	NI result;
	nimfr("getScreenHeight", "engine.nim")
	result = 0;
	nimln(70, "engine.nim");
	result = ((NI) (screenheight_142007));
	popFrame();
	return result;
}

static N_INLINE(void, destroy_133201)(Surface122290* surface) {
	nimfr("destroy", "sdl2.nim")
	nimln(1668, "sdl2.nim");
	Dl_131725(surface);
	popFrame();
}

N_NIMCALL(void, rendertext_142287)(NCSTRING textstring, NI32 x, NI32 y, NU8 color) {
	Surface122290* textsurface;
	TextureptrHEX3Aobjecttype121578* texttexture;
	NI32 textsizex;
	NI32 textsizey;
	NI32 LOC1;
	Box140009 textposition;
	NI32 LOC2;
	nimfr("renderText", "engine.nim")
	nimln(74, "engine.nim");
	if ((NU)(color) >= (NU)(fontcolor_142017->Sup.len)) raiseIndexError();
	textsurface = Dl_137834(font_142013, textstring, fontcolor_142017->data[color]);
	nimln(75, "engine.nim");
	texttexture = Dl_131385(renderer_142009, textsurface);
	textsizex = 0;
	textsizey = 0;
	nimln(78, "engine.nim");
	LOC1 = 0;
	LOC1 = Dl_131403(texttexture, NIM_NIL, NIM_NIL, (&textsizex), (&textsizey));
	nimln(79, "engine.nim");
	textposition.Field0 = x;
	textposition.Field1 = y;
	textposition.Field2 = textsizex;
	textposition.Field3 = textsizey;
	nimln(81, "engine.nim");
	LOC2 = 0;
	LOC2 = Dl_131622(renderer_142009, texttexture, NIM_NIL, (&textposition));
	nimln(86, "engine.nim");
	destroy_133201(textsurface);
	nimln(87, "engine.nim");
	Dl_131068(texttexture);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_engineInit)(void) {
	nimfr("engine", "engine.nim")
	nimln(6, "engine.nim");
	screenwidth_142005 = ((NI32) 640);
	nimln(7, "engine.nim");
	screenheight_142007 = ((NI32) 480);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_engineDatInit)(void) {
NTI142011.size = sizeof(TY142011*);
NTI142011.kind = 24;
NTI142011.base = (&NTI140009);
NTI142011.flags = 2;
NTI142011.marker = TMP310;
NTI142015.size = sizeof(TY142015*);
NTI142015.kind = 24;
NTI142015.base = (&NTI122280);
NTI142015.flags = 2;
NTI142015.marker = TMP319;
}

