/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\entity.o c:\users\john\documents\nim\bomberman\nimcache\entity.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct Entityobj149007 Entityobj149007;
typedef struct IvisibleHEX3Aobjecttype146058 IvisibleHEX3Aobjecttype146058;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct IcollidableHEX3Aobjecttype147018 IcollidableHEX3Aobjecttype147018;
typedef struct IupdatableHEX3Aobjecttype148021 IupdatableHEX3Aobjecttype148021;
typedef struct SpriteHEX3Aobjecttype141009 SpriteHEX3Aobjecttype141009;
typedef struct Box140009 Box140009;
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Entityobj149007  {
  TNimObject Sup;
IvisibleHEX3Aobjecttype146058* visible;
IcollidableHEX3Aobjecttype147018* collidable;
IupdatableHEX3Aobjecttype148021* updatable;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  IvisibleHEX3Aobjecttype146058  {
  TNimObject Sup;
SpriteHEX3Aobjecttype141009* sprite;
};
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  IcollidableHEX3Aobjecttype147018  {
  TNimObject Sup;
Box140009 box;
};
struct  IupdatableHEX3Aobjecttype148021  {
  TNimObject Sup;
};
struct  SpriteHEX3Aobjecttype141009  {
Box140009 box;
NU8 spritetype;
};
N_NIMCALL(void, move_149014)(Entityobj149007* obj, NI32 x, NI32 y);
N_NIMCALL(void, move_146139)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y);
N_NIMCALL(void, move_147110)(IcollidableHEX3Aobjecttype147018* impl, NI32 x, NI32 y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, moveto_149028)(Entityobj149007* obj, NI32 x, NI32 y);
N_NIMCALL(void, moveto_146144)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y);
N_NIMCALL(void, moveto_147115)(IcollidableHEX3Aobjecttype147018* impl, NI32 x, NI32 y);
N_NIMCALL(void, draw_149042)(Entityobj149007* obj);
N_NIMCALL(void, draw_146107)(IvisibleHEX3Aobjecttype146058* impl);
N_NIMCALL(void, collide_149051)(Entityobj149007* obj);
N_NIMCALL(void, collide_147067)(IcollidableHEX3Aobjecttype147018* impl);
N_NIMCALL(void, update_149060)(Entityobj149007* obj);
N_NIMCALL(void, update_148062)(IupdatableHEX3Aobjecttype148021* obj, IcollidableHEX3Aobjecttype147018* collisionimpl, IvisibleHEX3Aobjecttype146058* visibleimpl);
extern TFrame* frameptr_17042;
extern TNimType NTI3411; /* RootObj */
TNimType NTI149007; /* EntityObj */
extern TNimType NTI146053; /* IVisible */
extern TNimType NTI147013; /* ICollidable */
extern TNimType NTI148016; /* IUpdatable */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(void, move_149014)(Entityobj149007* obj, NI32 x, NI32 y) {
	nimfr("move", "entity.nim")
	nimln(13, "entity.nim");
	move_146139((*obj).visible, x, y);
	nimln(14, "entity.nim");
	move_147110((*obj).collidable, x, y);
	popFrame();
}

N_NIMCALL(void, moveto_149028)(Entityobj149007* obj, NI32 x, NI32 y) {
	nimfr("moveTo", "entity.nim")
	nimln(17, "entity.nim");
	moveto_146144((*obj).visible, x, y);
	nimln(18, "entity.nim");
	moveto_147115((*obj).collidable, x, y);
	popFrame();
}

N_NIMCALL(void, draw_149042)(Entityobj149007* obj) {
	nimfr("draw", "entity.nim")
	nimln(21, "entity.nim");
	draw_146107((*obj).visible);
	popFrame();
}

N_NIMCALL(void, collide_149051)(Entityobj149007* obj) {
	nimfr("collide", "entity.nim")
	nimln(24, "entity.nim");
	collide_147067((*obj).collidable);
	popFrame();
}

N_NIMCALL(void, update_149060)(Entityobj149007* obj) {
	nimfr("update", "entity.nim")
	nimln(27, "entity.nim");
	update_148062((*obj).updatable, (*obj).collidable, (*obj).visible);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_entityInit)(void) {
	nimfr("entity", "entity.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_entityDatInit)(void) {
static TNimNode* TMP360[3];
static TNimNode TMP335[4];
NTI149007.size = sizeof(Entityobj149007);
NTI149007.kind = 17;
NTI149007.base = (&NTI3411);
TMP360[0] = &TMP335[1];
TMP335[1].kind = 1;
TMP335[1].offset = offsetof(Entityobj149007, visible);
TMP335[1].typ = (&NTI146053);
TMP335[1].name = "visible";
TMP360[1] = &TMP335[2];
TMP335[2].kind = 1;
TMP335[2].offset = offsetof(Entityobj149007, collidable);
TMP335[2].typ = (&NTI147013);
TMP335[2].name = "collidable";
TMP360[2] = &TMP335[3];
TMP335[3].kind = 1;
TMP335[3].offset = offsetof(Entityobj149007, updatable);
TMP335[3].typ = (&NTI148016);
TMP335[3].name = "updatable";
TMP335[0].len = 3; TMP335[0].kind = 2; TMP335[0].sons = &TMP360[0];
NTI149007.node = &TMP335[0];
}

