/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\enums.o c:\users\john\documents\nim\bomberman\nimcache\enums.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI139007; /* SpriteE */
extern TFrame* frameptr_17042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_enumsInit)(void) {
	nimfr("enums", "enums.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_enumsDatInit)(void) {
static TNimNode* TMP304[6];
NI TMP306;
static char* NIM_CONST TMP305[6] = {
"player", 
"bullet", 
"wall", 
"bomb", 
"explosion", 
"numOfTextures"};
static TNimNode TMP292[7];
NTI139007.size = sizeof(NU8);
NTI139007.kind = 14;
NTI139007.base = 0;
NTI139007.flags = 3;
for (TMP306 = 0; TMP306 < 6; TMP306++) {
TMP292[TMP306+0].kind = 1;
TMP292[TMP306+0].offset = TMP306;
TMP292[TMP306+0].name = TMP305[TMP306];
TMP304[TMP306] = &TMP292[TMP306+0];
}
TMP292[6].len = 6; TMP292[6].kind = 2; TMP292[6].sons = &TMP304[0];
NTI139007.node = &TMP292[6];
}

