/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\game.o c:\users\john\documents\nim\bomberman\nimcache\game.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct TY154005 TY154005;
typedef struct BombHEX3Aobjecttype151022 BombHEX3Aobjecttype151022;
typedef struct TGenericSeq TGenericSeq;
typedef struct PlayerHEX3Aobjecttype152019 PlayerHEX3Aobjecttype152019;
typedef struct TY154009 TY154009;
typedef struct WallHEX3Aobjecttype153013 WallHEX3Aobjecttype153013;
typedef struct NimStringDesc NimStringDesc;
typedef struct Entityobj149007 Entityobj149007;
typedef struct Tcell46746 Tcell46746;
typedef struct TNimType TNimType;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct TNimNode TNimNode;
typedef struct Box140009 Box140009;
typedef struct TNimObject TNimObject;
typedef struct IvisibleHEX3Aobjecttype146058 IvisibleHEX3Aobjecttype146058;
typedef struct IcollidableHEX3Aobjecttype147018 IcollidableHEX3Aobjecttype147018;
typedef struct IupdatableHEX3Aobjecttype148021 IupdatableHEX3Aobjecttype148021;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
typedef struct SpriteHEX3Aobjecttype141009 SpriteHEX3Aobjecttype141009;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Entityobj149007  {
  TNimObject Sup;
IvisibleHEX3Aobjecttype146058* visible;
IcollidableHEX3Aobjecttype147018* collidable;
IupdatableHEX3Aobjecttype148021* updatable;
};
struct  BombHEX3Aobjecttype151022  {
  Entityobj149007 Sup;
};
struct  PlayerHEX3Aobjecttype152019  {
  Entityobj149007 Sup;
};
struct  WallHEX3Aobjecttype153013  {
  Entityobj149007 Sup;
};
typedef NI TY27820[16];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  IvisibleHEX3Aobjecttype146058  {
  TNimObject Sup;
SpriteHEX3Aobjecttype141009* sprite;
};
struct  IcollidableHEX3Aobjecttype147018  {
  TNimObject Sup;
Box140009 box;
};
struct  IupdatableHEX3Aobjecttype148021  {
  TNimObject Sup;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
struct  SpriteHEX3Aobjecttype141009  {
Box140009 box;
NU8 spritetype;
};
struct TY154005 {
  TGenericSeq Sup;
  BombHEX3Aobjecttype151022* data[SEQ_DECL_SIZE];
};
struct TY154009 {
  TGenericSeq Sup;
  WallHEX3Aobjecttype153013* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, update_154021)(void);
N_NIMCALL(void, update_149060)(Entityobj149007* obj);
N_NIMCALL(void, pollevents_150004)(NIM_BOOL* rungame);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, render_154030)(void);
N_NIMCALL(void, clear_142252)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, draw_149042)(Entityobj149007* obj);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
N_NIMCALL(void, rendertext_142287)(NCSTRING textstring, NI32 x, NI32 y, NU8 color);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, present_142261)(void);
N_NIMCALL(void, loadlevel_154449)(NimStringDesc* name);
N_NIMCALL(NimStringDesc*, readfile_13434)(NimStringDesc* filename);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(WallHEX3Aobjecttype153013*, newwall_153024)(NI32 x, NI32 y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_52622)(Tcell46746* c);
static N_INLINE(NIM_BOOL, canbecycleroot_50267)(Tcell46746* c);
static N_INLINE(void, rtladdcycleroot_51023)(Tcell46746* c);
N_NOINLINE(void, incl_47465)(Tcellset46758* s, Tcell46746* cell);
static N_INLINE(void, decref_52204)(Tcell46746* c);
N_NIMCALL(PlayerHEX3Aobjecttype152019*, newplayer_152024)(NI32 x, NI32 y);
N_NIMCALL(void, createbomb_154524)(NI32 x, NI32 y);
N_NIMCALL(BombHEX3Aobjecttype151022*, newbomb_151027)(NI32 x, NI32 y);
N_NIMCALL(void, initgame_154544)(void);
N_NIMCALL(void, initengine_142030)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP387)(void* p, NI op);
static N_INLINE(void, nimGCunref)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, TMP388)(void* p, NI op);
N_NIMCALL(void, wtf_154584)(void);
N_NIMCALL(void, findcollisions_154594)(Box140009* collidebox, NI* nbcollisions, Box140009** collisionptrs);
STRING_LITERAL(TMP372, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TMP374, "Score: ", 7);
STRING_LITERAL(TMP375, "maps/", 5);
STRING_LITERAL(TMP376, ".map", 4);
STRING_LITERAL(TMP386, "len(a) == L string modified while iterating over it", 51);
STRING_LITERAL(TMP389, "level1", 6);
STRING_LITERAL(TMP390, "wtf", 3);
NIM_BOOL rungame_154004;
TY154005* bombs_154006;
NI score_154007;
PlayerHEX3Aobjecttype152019* player1_154008;
TY154009* map_154010;
NimStringDesc* mapstring_154011;
NI32 tilesize_154012;
extern TFrame* frameptr_17042;
extern Tgcheap48616 gch_48644;
extern TNimType NTI151021; /* Bomb */
TNimType NTI154005; /* seq[Bomb] */
extern TNimType NTI153012; /* Wall */
TNimType NTI154009; /* seq[Wall] */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(void, update_154021)(void) {
	Entityobj149007* LOC1;
	nimfr("update", "game.nim")
	nimln(17, "game.nim");
	LOC1 = 0;
	LOC1 = &player1_154008->Sup;
	update_149060(LOC1);
	nimln(19, "game.nim");
	pollevents_150004((&rungame_154004));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(void, render_154030)(void) {
	Entityobj149007* LOC17;
	NimStringDesc* LOC18;
	NimStringDesc* LOC19;
	nimfr("render", "game.nim")
	nimln(22, "game.nim");
	clear_142252();
	{
		WallHEX3Aobjecttype153013* i_154211;
		NI i_154416;
		NI L_154418;
		i_154211 = 0;
		nimln(3084, "system.nim");
		i_154416 = ((NI) 0);
		nimln(3085, "system.nim");
		L_154418 = (map_154010 ? map_154010->Sup.len : 0);
		{
			nimln(3086, "system.nim");
			while (1) {
				Entityobj149007* LOC4;
				NI TMP371;
				if (!(i_154416 < L_154418)) goto LA3;
				nimln(3087, "system.nim");
				if ((NU)(i_154416) >= (NU)(map_154010->Sup.len)) raiseIndexError();
				i_154211 = map_154010->data[i_154416];
				nimln(24, "game.nim");
				LOC4 = 0;
				LOC4 = &i_154211->Sup;
				draw_149042(LOC4);
				nimln(3088, "system.nim");
				TMP371 = addInt(i_154416, ((NI) 1));
				i_154416 = (NI)(TMP371);
				nimln(3089, "system.nim");
				{
					if (!!(((map_154010 ? map_154010->Sup.len : 0) == L_154418))) goto LA7;
					failedassertimpl_88817(((NimStringDesc*) &TMP372));
				}
				LA7: ;
			} LA3: ;
		}
	}
	{
		BombHEX3Aobjecttype151022* i_154411;
		NI i_154422;
		NI L_154424;
		i_154411 = 0;
		nimln(3084, "system.nim");
		i_154422 = ((NI) 0);
		nimln(3085, "system.nim");
		L_154424 = (bombs_154006 ? bombs_154006->Sup.len : 0);
		{
			nimln(3086, "system.nim");
			while (1) {
				Entityobj149007* LOC12;
				NI TMP373;
				if (!(i_154422 < L_154424)) goto LA11;
				nimln(3087, "system.nim");
				if ((NU)(i_154422) >= (NU)(bombs_154006->Sup.len)) raiseIndexError();
				i_154411 = bombs_154006->data[i_154422];
				nimln(27, "game.nim");
				LOC12 = 0;
				LOC12 = &i_154411->Sup;
				draw_149042(LOC12);
				nimln(3088, "system.nim");
				TMP373 = addInt(i_154422, ((NI) 1));
				i_154422 = (NI)(TMP373);
				nimln(3089, "system.nim");
				{
					if (!!(((bombs_154006 ? bombs_154006->Sup.len : 0) == L_154424))) goto LA15;
					failedassertimpl_88817(((NimStringDesc*) &TMP372));
				}
				LA15: ;
			} LA11: ;
		}
	}
	nimln(29, "game.nim");
	LOC17 = 0;
	LOC17 = &player1_154008->Sup;
	draw_149042(LOC17);
	nimln(30, "game.nim");
	LOC18 = 0;
	LOC19 = 0;
	LOC19 = nimIntToStr(score_154007);
	LOC18 = rawNewString(LOC19->Sup.len + 7);
appendString(LOC18, ((NimStringDesc*) &TMP374));
appendString(LOC18, LOC19);
	rendertext_142287(LOC18->data, ((NI32) 5), ((NI32) 5), ((NU8) 2));
	nimln(31, "game.nim");
	present_142261();
	popFrame();
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_50267)(Tcell46746* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_51023)(Tcell46746* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(139, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(191, "gc.nim");
		incl_47465((&gch_48644.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_52622)(Tcell46746* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	(*c).refcount = (NI)((NU32)((*c).refcount) + (NU32)(((NI) 8)));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_50267(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_51023(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_52204)(Tcell46746* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_51804(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_50267(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_51023(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		Tcell46746* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = usrtocell_50246(src);
		incref_52622(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		Tcell46746* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = 0;
		LOC10 = usrtocell_50246((*dest));
		decref_52204(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, loadlevel_154449)(NimStringDesc* name) {
	NimStringDesc* LOC1;
	NI32 x;
	NI32 y;
	nimfr("loadLevel", "game.nim")
	nimln(34, "game.nim");
	LOC1 = 0;
	LOC1 = rawNewString(name->Sup.len + 9);
appendString(LOC1, ((NimStringDesc*) &TMP375));
appendString(LOC1, name);
appendString(LOC1, ((NimStringDesc*) &TMP376));
	asgnRefNoCycle((void**) (&mapstring_154011), readfile_13434(LOC1));
	nimln(35, "game.nim");
	x = ((NI32) 0);
	y = ((NI32) 0);
	{
		NIM_CHAR character_154454;
		NI i_154506;
		NI L_154508;
		character_154454 = 0;
		nimln(3102, "system.nim");
		i_154506 = ((NI) 0);
		nimln(3103, "system.nim");
		L_154508 = (mapstring_154011 ? mapstring_154011->Sup.len : 0);
		{
			nimln(3104, "system.nim");
			while (1) {
				NimStringDesc* LOC5;
				NI TMP385;
				if (!(i_154506 < L_154508)) goto LA4;
				nimln(3105, "system.nim");
				if ((NU)(i_154506) > (NU)(mapstring_154011->Sup.len)) raiseIndexError();
				character_154454 = mapstring_154011->data[i_154506];
				nimln(37, "game.nim");
				LOC5 = 0;
				LOC5 = nimIntToStr(((NI) (x)));
				printf("%s\015\012", LOC5? (LOC5)->data:"nil");
				nimln(38, "game.nim");
				{
					NI32 TMP377;
					NI32 TMP378;
					WallHEX3Aobjecttype153013* LOC10;
					NI32 TMP379;
					if (!((NU8)(character_154454) == (NU8)(49))) goto LA8;
					nimln(39, "game.nim");
					TMP377 = mulInt(x, tilesize_154012);
					TMP378 = mulInt(y, tilesize_154012);
					LOC10 = 0;
					LOC10 = newwall_153024((NI32)(TMP377), (NI32)(TMP378));
					map_154010 = (TY154009*) incrSeq(&(map_154010)->Sup, sizeof(WallHEX3Aobjecttype153013*));
					asgnRef((void**) (&map_154010->data[map_154010->Sup.len-1]), LOC10);
					nimln(40, "game.nim");
					TMP379 = addInt(x, ((NI) 1));
					x = (NI32)(TMP379);
				}
				goto LA6;
				LA8: ;
				{
					NI32 TMP380;
					NI32 TMP381;
					NI32 TMP382;
					nimln(41, "game.nim");
					if (!((NU8)(character_154454) == (NU8)(80))) goto LA12;
					nimln(42, "game.nim");
					TMP380 = mulInt(x, tilesize_154012);
					TMP381 = mulInt(y, tilesize_154012);
					asgnRef((void**) (&player1_154008), newplayer_152024((NI32)(TMP380), (NI32)(TMP381)));
					nimln(43, "game.nim");
					TMP382 = addInt(x, ((NI) 1));
					x = (NI32)(TMP382);
				}
				goto LA6;
				LA12: ;
				{
					NI32 TMP383;
					nimln(44, "game.nim");
					if (!((NU8)(character_154454) == (NU8)(48))) goto LA15;
					nimln(45, "game.nim");
					TMP383 = addInt(x, ((NI) 1));
					x = (NI32)(TMP383);
				}
				goto LA6;
				LA15: ;
				{
					NI32 TMP384;
					nimln(46, "game.nim");
					if (!((NU8)(character_154454) == (NU8)(13))) goto LA18;
					nimln(47, "game.nim");
					TMP384 = addInt(y, ((NI) 1));
					y = (NI32)(TMP384);
					nimln(48, "game.nim");
					x = ((NI32) 0);
				}
				goto LA6;
				LA18: ;
				LA6: ;
				nimln(3106, "system.nim");
				TMP385 = addInt(i_154506, ((NI) 1));
				i_154506 = (NI)(TMP385);
				nimln(3107, "system.nim");
				{
					if (!!(((mapstring_154011 ? mapstring_154011->Sup.len : 0) == L_154508))) goto LA22;
					failedassertimpl_88817(((NimStringDesc*) &TMP386));
				}
				LA22: ;
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, createbomb_154524)(NI32 x, NI32 y) {
	BombHEX3Aobjecttype151022* LOC1;
	nimfr("createBomb", "game.nim")
	nimln(51, "game.nim");
	LOC1 = 0;
	LOC1 = newbomb_151027(x, y);
	bombs_154006 = (TY154005*) incrSeq(&(bombs_154006)->Sup, sizeof(BombHEX3Aobjecttype151022*));
	asgnRef((void**) (&bombs_154006->data[bombs_154006->Sup.len-1]), LOC1);
	popFrame();
}
N_NIMCALL(void, TMP387)(void* p, NI op) {
	TY154005* a;
	NI LOC1;
	a = (TY154005*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(void, nimGCunref)(void* p) {
	Tcell46746* LOC1;
	nimfr("nimGCunref", "gc.nim")
	nimln(223, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_50246(p);
	decref_52204(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP388)(void* p, NI op) {
	TY154009* a;
	NI LOC1;
	a = (TY154009*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

N_NIMCALL(void, initgame_154544)(void) {
	nimfr("initGame", "game.nim")
	nimln(54, "game.nim");
	initengine_142030();
	nimln(55, "game.nim");
	if (bombs_154006) nimGCunref(bombs_154006);
	bombs_154006 = (TY154005*) newSeqRC1((&NTI154005), 0);
	nimln(56, "game.nim");
	if (map_154010) nimGCunref(map_154010);
	map_154010 = (TY154009*) newSeqRC1((&NTI154009), 0);
	nimln(57, "game.nim");
	loadlevel_154449(((NimStringDesc*) &TMP389));
	nimln(58, "game.nim");
	createbomb_154524(((NI32) 50), ((NI32) 50));
	popFrame();
}

N_NIMCALL(void, wtf_154584)(void) {
	nimfr("wtf", "game.nim")
	nimln(61, "game.nim");
	printf("%s\015\012", ((NimStringDesc*) &TMP390)? (((NimStringDesc*) &TMP390))->data:"nil");
	popFrame();
}

N_NIMCALL(void, findcollisions_154594)(Box140009* collidebox, NI* nbcollisions, Box140009** collisionptrs) {
	nimfr("findCollisions", "game.nim")
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_gameInit)(void) {
	nimfr("game", "game.nim")
	nimln(8, "game.nim");
	rungame_154004 = NIM_TRUE;
	nimln(14, "game.nim");
	tilesize_154012 = ((NI32) 40);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_gameDatInit)(void) {
NTI154005.size = sizeof(TY154005*);
NTI154005.kind = 24;
NTI154005.base = (&NTI151021);
NTI154005.marker = TMP387;
NTI154009.size = sizeof(TY154009*);
NTI154009.kind = 24;
NTI154009.base = (&NTI153012);
NTI154009.marker = TMP388;
}

