/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\input.o c:\users\john\documents\nim\bomberman\nimcache\input.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct Event121164 Event121164;
typedef struct Tvector2d143047 Tvector2d143047;
typedef struct Keyboardeventobj121176 Keyboardeventobj121176;
typedef struct Keysym121270 Keysym121270;
typedef NU8 TY121349[52];
struct  Event121164  {
NI32 kind;
TY121349 padding;
};
typedef NIM_BOOL TY146013[513];
struct  Tvector2d143047  {
NF x;
NF y;
};
typedef NIM_BOOL TY146026[4];
typedef NIM_BOOL TY146028[4];
typedef N_CDECL_PTR(NI32, TY132628) (Event121164* event);
struct  Keysym121270  {
NI32 scancode;
int sym;
NI16 modstate;
int unicode;
};
struct  Keyboardeventobj121176  {
NI32 kind;
NU32 timestamp;
NU32 windowid;
NU8 state;
NIM_BOOL repeat;
NU8 pad1;
NU8 pad2;
Keysym121270 keysym;
};
typedef N_CDECL_PTR(NU8, TY132500) (int* x, int* y);
N_NIMCALL(void, pollevents_150004)(NIM_BOOL* rungame);
N_NIMCALL(NIM_BOOL, tobool_121657)(NI32 some);
N_NIMCALL(Keyboardeventobj121176*, Evkeyboard_122813)(Event121164* event_122810);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
NIM_CONST TY146028 TMP334 = {NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_FALSE}
;
Event121164 e_146010;
extern Event121164 defaultevent_133420;
NI32 mousex_146011;
NI32 mousey_146012;
TY146013 keyspressed_146024;
Tvector2d143047 playertempmovement_146025;
TY146026 collisiondirections_146030;
extern TY132628 Dl_132627;
extern TY132500 Dl_132499;
extern TFrame* frameptr_17042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(void, pollevents_150004)(NIM_BOOL* rungame) {
	NU8 LOC9;
	nimfr("pollEvents", "input.nim")
	{
		nimln(14, "input.nim");
		while (1) {
			NI32 LOC3;
			NIM_BOOL LOC4;
			LOC3 = 0;
			LOC3 = Dl_132627((&e_146010));
			LOC4 = 0;
			LOC4 = tobool_121657(LOC3);
			if (!LOC4) goto LA2;
			nimln(15, "input.nim");
			switch (e_146010.kind) {
			case ((NI32) 256):
			{
				nimln(17, "input.nim");
				(*rungame) = NIM_FALSE;
				nimln(18, "input.nim");
				goto LA1;
			}
			break;
			case ((NI32) 768):
			{
				Keyboardeventobj121176* keyevent;
				nimln(20, "input.nim");
				keyevent = Evkeyboard_122813((&e_146010));
				nimln(21, "input.nim");
				keyspressed_146024[((*keyevent).keysym.scancode)- 0] = NIM_TRUE;
			}
			break;
			case ((NI32) 769):
			{
				Keyboardeventobj121176* keyevent;
				nimln(23, "input.nim");
				keyevent = Evkeyboard_122813((&e_146010));
				nimln(24, "input.nim");
				keyspressed_146024[((*keyevent).keysym.scancode)- 0] = NIM_FALSE;
			}
			break;
			default:
			{
			}
			break;
			}
		} LA2: ;
	} LA1: ;
	nimln(29, "input.nim");
	LOC9 = 0;
	LOC9 = Dl_132499((&mousex_146011), (&mousey_146012));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_inputInit)(void) {
	nimfr("input", "input.nim")
	nimln(6, "input.nim");
	e_146010 = defaultevent_133420;
	nimln(10, "input.nim");
	memcpy((void*)collisiondirections_146030, (NIM_CONST void*)TMP334, sizeof(collisiondirections_146030));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_inputDatInit)(void) {
}

