/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\iupdatable.o c:\users\john\documents\nim\bomberman\nimcache\iupdatable.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdio.h>
typedef struct UpdatableplayerHEX3Aobjecttype148023 UpdatableplayerHEX3Aobjecttype148023;
typedef struct IupdatableHEX3Aobjecttype148021 IupdatableHEX3Aobjecttype148021;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tvector2d143047 Tvector2d143047;
typedef struct UpdatablebombHEX3Aobjecttype148026 UpdatablebombHEX3Aobjecttype148026;
typedef struct IcollidableHEX3Aobjecttype147018 IcollidableHEX3Aobjecttype147018;
typedef struct IvisibleHEX3Aobjecttype146058 IvisibleHEX3Aobjecttype146058;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Box140009 Box140009;
typedef struct SpriteHEX3Aobjecttype141009 SpriteHEX3Aobjecttype141009;
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  IupdatableHEX3Aobjecttype148021  {
  TNimObject Sup;
};
struct  Tvector2d143047  {
NF x;
NF y;
};
struct  UpdatableplayerHEX3Aobjecttype148023  {
  IupdatableHEX3Aobjecttype148021 Sup;
Tvector2d143047 playertempmovement;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  UpdatablebombHEX3Aobjecttype148026  {
  IupdatableHEX3Aobjecttype148021 Sup;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_BOOL TY146013[513];
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  IcollidableHEX3Aobjecttype147018  {
  TNimObject Sup;
Box140009 box;
};
struct  IvisibleHEX3Aobjecttype146058  {
  TNimObject Sup;
SpriteHEX3Aobjecttype141009* sprite;
};
struct  SpriteHEX3Aobjecttype141009  {
Box140009 box;
NU8 spritetype;
};
N_NIMCALL(UpdatableplayerHEX3Aobjecttype148023*, newupdatableplayer_148031)(void);
N_NIMCALL(void, TMP353)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(UpdatablebombHEX3Aobjecttype148026*, newupdatablebomb_148041)(void);
N_NIMCALL(void, TMP354)(void* p, NI op);
N_NIMCALL(void, update_148051)(IupdatableHEX3Aobjecttype148021* obj, IcollidableHEX3Aobjecttype147018* collisionimpl, IvisibleHEX3Aobjecttype146058* visibleimpl);
N_NIMCALL(void, update_148067)(UpdatableplayerHEX3Aobjecttype148023* obj, IcollidableHEX3Aobjecttype147018* collisionimpl, IvisibleHEX3Aobjecttype146058* visibleimpl);
N_NIMCALL(void, move_147110)(IcollidableHEX3Aobjecttype147018* impl, NI32 x, NI32 y);
N_NIMCALL(void, move_146139)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y);
static N_INLINE(Tvector2d143047, vector2d_143072)(NF x, NF y);
static N_INLINE(void, HEX2BHEX3D_107689)(NF* x, NF y);
static N_INLINE(void, HEX2DHEX3D_144158)(NF* x, NF y);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(void, update_148164)(UpdatablebombHEX3Aobjecttype148026* obj);
N_NIMCALL(void, TMP363)(void* p, NI op);
STRING_LITERAL(TMP355, "shouldn\'t be called", 19);
STRING_LITERAL(TMP356, "xwhat", 5);
extern TNimType NTI3411; /* RootObj */
TNimType NTI148021; /* IUpdatable:ObjectType */
TNimType NTI148023; /* UpdatablePlayer:ObjectType */
extern TNimType NTI143047; /* TVector2d */
TNimType NTI148018; /* UpdatablePlayer */
extern TFrame* frameptr_17042;
TNimType NTI148026; /* UpdatableBomb:ObjectType */
TNimType NTI148020; /* UpdatableBomb */
extern TY146013 keyspressed_146024;
TNimType NTI148016; /* IUpdatable */
N_NIMCALL(void, TMP353)(void* p, NI op) {
	UpdatableplayerHEX3Aobjecttype148023* a;
	a = (UpdatableplayerHEX3Aobjecttype148023*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(UpdatableplayerHEX3Aobjecttype148023*, newupdatableplayer_148031)(void) {
	UpdatableplayerHEX3Aobjecttype148023* result;
	UpdatableplayerHEX3Aobjecttype148023* LOC1;
	nimfr("newUpdatablePlayer", "iupdatable.nim")
	result = 0;
	nimln(15, "iupdatable.nim");
	LOC1 = 0;
	LOC1 = (UpdatableplayerHEX3Aobjecttype148023*) newObj((&NTI148018), sizeof(UpdatableplayerHEX3Aobjecttype148023));
	(*LOC1).Sup.Sup.m_type = (&NTI148023);
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP354)(void* p, NI op) {
	UpdatablebombHEX3Aobjecttype148026* a;
	a = (UpdatablebombHEX3Aobjecttype148026*)p;
}

N_NIMCALL(UpdatablebombHEX3Aobjecttype148026*, newupdatablebomb_148041)(void) {
	UpdatablebombHEX3Aobjecttype148026* result;
	UpdatablebombHEX3Aobjecttype148026* LOC1;
	nimfr("newUpdatableBomb", "iupdatable.nim")
	result = 0;
	nimln(18, "iupdatable.nim");
	LOC1 = 0;
	LOC1 = (UpdatablebombHEX3Aobjecttype148026*) newObj((&NTI148020), sizeof(UpdatablebombHEX3Aobjecttype148026));
	(*LOC1).Sup.Sup.m_type = (&NTI148026);
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(void, update_148051)(IupdatableHEX3Aobjecttype148021* obj, IcollidableHEX3Aobjecttype147018* collisionimpl, IvisibleHEX3Aobjecttype146058* visibleimpl) {
	nimfr("update", "iupdatable.nim")
	nimln(22, "iupdatable.nim");
	printf("%s\015\012", ((NimStringDesc*) &TMP355)? (((NimStringDesc*) &TMP355))->data:"nil");
	popFrame();
}

static N_INLINE(Tvector2d143047, vector2d_143072)(NF x, NF y) {
	Tvector2d143047 result;
	nimfr("vector2d", "basic2d.nim")
	nimln(335, "basic2d.nim");
	result.x = x;
	nimln(336, "basic2d.nim");
	result.y = y;
	popFrame();
	return result;
}

static N_INLINE(void, HEX2BHEX3D_107689)(NF* x, NF y) {
	nimfr("+=", "system.nim")
	nimln(2992, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

static N_INLINE(void, HEX2DHEX3D_144158)(NF* x, NF y) {
	nimfr("-=", "system.nim")
	nimln(2996, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

N_NIMCALL(void, update_148067)(UpdatableplayerHEX3Aobjecttype148023* obj, IcollidableHEX3Aobjecttype147018* collisionimpl, IvisibleHEX3Aobjecttype146058* visibleimpl) {
	NimStringDesc* LOC17;
	nimfr("update", "iupdatable.nim")
	nimln(27, "iupdatable.nim");
	move_147110(collisionimpl, ((NI32) ((*obj).playertempmovement.x)), ((NI32) ((*obj).playertempmovement.y)));
	nimln(29, "iupdatable.nim");
	move_146139(visibleimpl, ((NI32) ((*obj).playertempmovement.x)), ((NI32) ((*obj).playertempmovement.y)));
	nimln(32, "iupdatable.nim");
	(*obj).playertempmovement = vector2d_143072(0.0, 0.0);
	nimln(33, "iupdatable.nim");
	{
		if (!keyspressed_146024[(((NI) 7))- 0]) goto LA3;
		nimln(34, "iupdatable.nim");
		printf("%s\015\012", ((NimStringDesc*) &TMP356)? (((NimStringDesc*) &TMP356))->data:"nil");
		nimln(35, "iupdatable.nim");
		HEX2BHEX3D_107689((&(*obj).playertempmovement.x), 5.0000000000000000e+000);
	}
	LA3: ;
	nimln(36, "iupdatable.nim");
	{
		if (!keyspressed_146024[(((NI) 4))- 0]) goto LA7;
		nimln(37, "iupdatable.nim");
		HEX2DHEX3D_144158((&(*obj).playertempmovement.x), 5.0000000000000000e+000);
	}
	LA7: ;
	nimln(38, "iupdatable.nim");
	{
		if (!keyspressed_146024[(((NI) 22))- 0]) goto LA11;
		nimln(39, "iupdatable.nim");
		HEX2BHEX3D_107689((&(*obj).playertempmovement.y), 5.0000000000000000e+000);
	}
	LA11: ;
	nimln(40, "iupdatable.nim");
	{
		if (!keyspressed_146024[(((NI) 26))- 0]) goto LA15;
		nimln(41, "iupdatable.nim");
		HEX2DHEX3D_144158((&(*obj).playertempmovement.y), 5.0000000000000000e+000);
	}
	LA15: ;
	nimln(42, "iupdatable.nim");
	LOC17 = 0;
	LOC17 = nimFloatToStr((*obj).playertempmovement.x);
	printf("%s\015\012", LOC17? (LOC17)->data:"nil");
	popFrame();
}

N_NIMCALL(void, update_148164)(UpdatablebombHEX3Aobjecttype148026* obj) {
	nimfr("update", "iupdatable.nim")
	popFrame();
}
N_NIMCALL(void, TMP363)(void* p, NI op) {
	IupdatableHEX3Aobjecttype148021* a;
	a = (IupdatableHEX3Aobjecttype148021*)p;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_iupdatableInit)(void) {
	nimfr("iupdatable", "iupdatable.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_iupdatableDatInit)(void) {
static TNimNode TMP350[3];
NTI148021.size = sizeof(IupdatableHEX3Aobjecttype148021);
NTI148021.kind = 17;
NTI148021.base = (&NTI3411);
NTI148021.flags = 1;
TMP350[0].len = 0; TMP350[0].kind = 2;
NTI148021.node = &TMP350[0];
NTI148023.size = sizeof(UpdatableplayerHEX3Aobjecttype148023);
NTI148023.kind = 17;
NTI148023.base = (&NTI148021);
NTI148023.flags = 1;
TMP350[1].kind = 1;
TMP350[1].offset = offsetof(UpdatableplayerHEX3Aobjecttype148023, playertempmovement);
TMP350[1].typ = (&NTI143047);
TMP350[1].name = "playerTempMovement";
NTI148023.node = &TMP350[1];
NTI148018.size = sizeof(UpdatableplayerHEX3Aobjecttype148023*);
NTI148018.kind = 22;
NTI148018.base = (&NTI148023);
NTI148018.marker = TMP353;
NTI148026.size = sizeof(UpdatablebombHEX3Aobjecttype148026);
NTI148026.kind = 17;
NTI148026.base = (&NTI148021);
NTI148026.flags = 1;
TMP350[2].len = 0; TMP350[2].kind = 2;
NTI148026.node = &TMP350[2];
NTI148020.size = sizeof(UpdatablebombHEX3Aobjecttype148026*);
NTI148020.kind = 22;
NTI148020.base = (&NTI148026);
NTI148020.marker = TMP354;
NTI148016.size = sizeof(IupdatableHEX3Aobjecttype148021*);
NTI148016.kind = 22;
NTI148016.base = (&NTI148021);
NTI148016.marker = TMP363;
}

