/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\ivisible.o c:\users\john\documents\nim\bomberman\nimcache\ivisible.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdio.h>
typedef struct VisiblenormalHEX3Aobjecttype146061 VisiblenormalHEX3Aobjecttype146061;
typedef struct IvisibleHEX3Aobjecttype146058 IvisibleHEX3Aobjecttype146058;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct SpriteHEX3Aobjecttype141009 SpriteHEX3Aobjecttype141009;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct InvisibleHEX3Aobjecttype146063 InvisibleHEX3Aobjecttype146063;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Box140009 Box140009;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  IvisibleHEX3Aobjecttype146058  {
  TNimObject Sup;
SpriteHEX3Aobjecttype141009* sprite;
};
struct  VisiblenormalHEX3Aobjecttype146061  {
  IvisibleHEX3Aobjecttype146058 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
struct  InvisibleHEX3Aobjecttype146063  {
  IvisibleHEX3Aobjecttype146058 Sup;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  SpriteHEX3Aobjecttype141009  {
Box140009 box;
NU8 spritetype;
};
typedef NI TY27820[16];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
N_NIMCALL(VisiblenormalHEX3Aobjecttype146061*, newvisiblenormal_146068)(NI32 x, NI32 y, NI32 w, NI32 h, NU8 sprite);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP339)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(SpriteHEX3Aobjecttype141009*, newsprite_141016)(NI32 x, NI32 y, NI32 w, NI32 h, NU8 spritetype);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(InvisibleHEX3Aobjecttype146063*, newinvisible_146083)(NI32 x, NI32 y, NI32 w, NI32 h, NU8 sprite);
N_NIMCALL(void, TMP340)(void* p, NI op);
N_NIMCALL(void, draw_146098)(IvisibleHEX3Aobjecttype146058* impl);
N_NIMCALL(void, draw_146112)(VisiblenormalHEX3Aobjecttype146061* impl);
N_NIMCALL(void, drawsprite_142207)(SpriteHEX3Aobjecttype141009* sprite);
N_NIMCALL(void, draw_146121)(InvisibleHEX3Aobjecttype146063* impl);
N_NIMCALL(void, move_146130)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y);
N_NIMCALL(void, move_141032)(SpriteHEX3Aobjecttype141009* obj, NI32 x, NI32 y);
N_NIMCALL(void, moveto_146144)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y);
N_NIMCALL(void, moveto_141061)(SpriteHEX3Aobjecttype141009* obj, NI32 x, NI32 y);
N_NIMCALL(void, TMP361)(void* p, NI op);
STRING_LITERAL(TMP341, "ivisible Should be overriden !", 30);
extern TNimType NTI3411; /* RootObj */
TNimType NTI146058; /* IVisible:ObjectType */
extern TNimType NTI141008; /* Sprite */
TNimType NTI146061; /* VisibleNormal:ObjectType */
TNimType NTI146055; /* VisibleNormal */
extern TFrame* frameptr_17042;
extern Tgcheap48616 gch_48644;
TNimType NTI146063; /* Invisible:ObjectType */
TNimType NTI146057; /* Invisible */
TNimType NTI146053; /* IVisible */
N_NIMCALL(void, TMP339)(void* p, NI op) {
	VisiblenormalHEX3Aobjecttype146061* a;
	a = (VisiblenormalHEX3Aobjecttype146061*)p;
	nimGCvisit((void*)(*a).Sup.sprite, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(VisiblenormalHEX3Aobjecttype146061*, newvisiblenormal_146068)(NI32 x, NI32 y, NI32 w, NI32 h, NU8 sprite) {
	VisiblenormalHEX3Aobjecttype146061* result;
	VisiblenormalHEX3Aobjecttype146061* LOC1;
	nimfr("newVisibleNormal", "ivisible.nim")
	result = 0;
	nimln(13, "ivisible.nim");
	LOC1 = 0;
	LOC1 = (VisiblenormalHEX3Aobjecttype146061*) newObj((&NTI146055), sizeof(VisiblenormalHEX3Aobjecttype146061));
	(*LOC1).Sup.Sup.m_type = (&NTI146061);
	asgnRefNoCycle((void**) (&(*LOC1).Sup.sprite), newsprite_141016(x, y, w, h, sprite));
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP340)(void* p, NI op) {
	InvisibleHEX3Aobjecttype146063* a;
	a = (InvisibleHEX3Aobjecttype146063*)p;
	nimGCvisit((void*)(*a).Sup.sprite, op);
}

N_NIMCALL(InvisibleHEX3Aobjecttype146063*, newinvisible_146083)(NI32 x, NI32 y, NI32 w, NI32 h, NU8 sprite) {
	InvisibleHEX3Aobjecttype146063* result;
	InvisibleHEX3Aobjecttype146063* LOC1;
	nimfr("newInvisible", "ivisible.nim")
	result = 0;
	nimln(16, "ivisible.nim");
	LOC1 = 0;
	LOC1 = (InvisibleHEX3Aobjecttype146063*) newObj((&NTI146057), sizeof(InvisibleHEX3Aobjecttype146063));
	(*LOC1).Sup.Sup.m_type = (&NTI146063);
	asgnRefNoCycle((void**) (&(*LOC1).Sup.sprite), newsprite_141016(x, y, w, h, sprite));
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(void, draw_146098)(IvisibleHEX3Aobjecttype146058* impl) {
	nimfr("draw", "ivisible.nim")
	nimln(19, "ivisible.nim");
	printf("%s\015\012", ((NimStringDesc*) &TMP341)? (((NimStringDesc*) &TMP341))->data:"nil");
	popFrame();
}

N_NIMCALL(void, draw_146112)(VisiblenormalHEX3Aobjecttype146061* impl) {
	nimfr("draw", "ivisible.nim")
	nimln(22, "ivisible.nim");
	drawsprite_142207((*impl).Sup.sprite);
	popFrame();
}

N_NIMCALL(void, draw_146121)(InvisibleHEX3Aobjecttype146063* impl) {
	nimfr("draw", "ivisible.nim")
	popFrame();
}

N_NIMCALL(void, move_146130)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y) {
	nimfr("move", "ivisible.nim")
	nimln(28, "ivisible.nim");
	move_141032((*impl).sprite, x, y);
	popFrame();
}

N_NIMCALL(void, moveto_146144)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y) {
	nimfr("moveTo", "ivisible.nim")
	nimln(31, "ivisible.nim");
	moveto_141061((*impl).sprite, x, y);
	popFrame();
}
N_NIMCALL(void, TMP361)(void* p, NI op) {
	IvisibleHEX3Aobjecttype146058* a;
	a = (IvisibleHEX3Aobjecttype146058*)p;
	nimGCvisit((void*)(*a).sprite, op);
}
NIM_EXTERNC N_NOINLINE(void, HEX00_ivisibleInit)(void) {
	nimfr("ivisible", "ivisible.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_ivisibleDatInit)(void) {
static TNimNode TMP337[3];
NTI146058.size = sizeof(IvisibleHEX3Aobjecttype146058);
NTI146058.kind = 17;
NTI146058.base = (&NTI3411);
TMP337[0].kind = 1;
TMP337[0].offset = offsetof(IvisibleHEX3Aobjecttype146058, sprite);
TMP337[0].typ = (&NTI141008);
TMP337[0].name = "sprite";
NTI146058.node = &TMP337[0];
NTI146061.size = sizeof(VisiblenormalHEX3Aobjecttype146061);
NTI146061.kind = 17;
NTI146061.base = (&NTI146058);
TMP337[1].len = 0; TMP337[1].kind = 2;
NTI146061.node = &TMP337[1];
NTI146055.size = sizeof(VisiblenormalHEX3Aobjecttype146061*);
NTI146055.kind = 22;
NTI146055.base = (&NTI146061);
NTI146055.marker = TMP339;
NTI146063.size = sizeof(InvisibleHEX3Aobjecttype146063);
NTI146063.kind = 17;
NTI146063.base = (&NTI146058);
TMP337[2].len = 0; TMP337[2].kind = 2;
NTI146063.node = &TMP337[2];
NTI146057.size = sizeof(InvisibleHEX3Aobjecttype146063*);
NTI146057.kind = 22;
NTI146057.base = (&NTI146063);
NTI146057.marker = TMP340;
NTI146053.size = sizeof(IvisibleHEX3Aobjecttype146058*);
NTI146053.kind = 22;
NTI146053.base = (&NTI146058);
NTI146053.marker = TMP361;
}

