/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\main.o c:\users\john\documents\nim\bomberman\nimcache\main.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct IvisibleHEX3Aobjecttype146058 IvisibleHEX3Aobjecttype146058;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct InvisibleHEX3Aobjecttype146063 InvisibleHEX3Aobjecttype146063;
typedef struct VisiblenormalHEX3Aobjecttype146061 VisiblenormalHEX3Aobjecttype146061;
typedef struct IcollidableHEX3Aobjecttype147018 IcollidableHEX3Aobjecttype147018;
typedef struct NotcollidableHEX3Aobjecttype147023 NotcollidableHEX3Aobjecttype147023;
typedef struct IupdatableHEX3Aobjecttype148021 IupdatableHEX3Aobjecttype148021;
typedef struct UpdatableplayerHEX3Aobjecttype148023 UpdatableplayerHEX3Aobjecttype148023;
typedef struct UpdatablebombHEX3Aobjecttype148026 UpdatablebombHEX3Aobjecttype148026;
typedef struct Entityobj149007 Entityobj149007;
typedef struct TNimObject TNimObject;
typedef struct SpriteHEX3Aobjecttype141009 SpriteHEX3Aobjecttype141009;
typedef struct Box140009 Box140009;
typedef struct Tvector2d143047 Tvector2d143047;
typedef N_CDECL_PTR(NI32, TY131273) (int flags);
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  IvisibleHEX3Aobjecttype146058  {
  TNimObject Sup;
SpriteHEX3Aobjecttype141009* sprite;
};
struct  InvisibleHEX3Aobjecttype146063  {
  IvisibleHEX3Aobjecttype146058 Sup;
};
struct  VisiblenormalHEX3Aobjecttype146061  {
  IvisibleHEX3Aobjecttype146058 Sup;
};
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  IcollidableHEX3Aobjecttype147018  {
  TNimObject Sup;
Box140009 box;
};
struct  NotcollidableHEX3Aobjecttype147023  {
  IcollidableHEX3Aobjecttype147018 Sup;
};
struct  IupdatableHEX3Aobjecttype148021  {
  TNimObject Sup;
};
struct  Tvector2d143047  {
NF x;
NF y;
};
struct  UpdatableplayerHEX3Aobjecttype148023  {
  IupdatableHEX3Aobjecttype148021 Sup;
Tvector2d143047 playertempmovement;
};
struct  UpdatablebombHEX3Aobjecttype148026  {
  IupdatableHEX3Aobjecttype148021 Sup;
};
struct  Entityobj149007  {
  TNimObject Sup;
IvisibleHEX3Aobjecttype146058* visible;
IcollidableHEX3Aobjecttype147018* collidable;
IupdatableHEX3Aobjecttype148021* updatable;
};
struct  SpriteHEX3Aobjecttype141009  {
Box140009 box;
NU8 spritetype;
};
N_NIMCALL(void, randomize_112024)(void);
N_NIMCALL(void, initgame_154544)(void);
N_NIMCALL(void, update_154021)(void);
N_NIMCALL(void, render_154030)(void);
N_NIMCALL(void, draw_146121)(InvisibleHEX3Aobjecttype146063* impl);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(void, draw_146112)(VisiblenormalHEX3Aobjecttype146061* impl);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NOINLINE(NIM_BOOL, isobjslowpath_23217)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NIMCALL(void, draw_146098)(IvisibleHEX3Aobjecttype146058* impl);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, move_146130)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y);
N_NIMCALL(void, collide_147072)(NotcollidableHEX3Aobjecttype147023* impl);
N_NIMCALL(void, collide_147058)(IcollidableHEX3Aobjecttype147018* impl);
N_NIMCALL(void, move_147083)(IcollidableHEX3Aobjecttype147018* impl, NI32 x, NI32 y);
N_NIMCALL(void, update_148067)(UpdatableplayerHEX3Aobjecttype148023* obj, IcollidableHEX3Aobjecttype147018* collisionimpl, IvisibleHEX3Aobjecttype146058* visibleimpl);
N_NIMCALL(void, update_148051)(IupdatableHEX3Aobjecttype148021* obj, IcollidableHEX3Aobjecttype147018* collisionimpl, IvisibleHEX3Aobjecttype146058* visibleimpl);
N_NIMCALL(void, update_148164)(UpdatablebombHEX3Aobjecttype148026* obj);
N_NIMCALL(void, move_149014)(Entityobj149007* obj, NI32 x, NI32 y);
N_NIMCALL(void, moveto_149028)(Entityobj149007* obj, NI32 x, NI32 y);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_ttfInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_ttfDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_enumsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_enumsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_boxInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_boxDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_spriteInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_spriteDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_engineInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_engineDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_ivisibleInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_ivisibleDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_icollidableInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_icollidableDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_iupdatableInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_iupdatableDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_entityInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_entityDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_inputInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_inputDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_bombInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_bombDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_playerInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_playerDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_wallInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_wallDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gameInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_gameDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, mainInit)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit)(void);
extern TY131273 Dl_131272;
extern NIM_BOOL rungame_154004;
extern TNimType NTI146063; /* Invisible:ObjectType */
extern TNimType NTI146061; /* VisibleNormal:ObjectType */
extern TNimType NTI146058; /* IVisible:ObjectType */
static TNimType* Nim_OfCheck_CACHE1[2];
extern TFrame* frameptr_17042;
extern TNimType NTI147023; /* NotCollidable:ObjectType */
extern TNimType NTI147018; /* ICollidable:ObjectType */
static TNimType* Nim_OfCheck_CACHE2[2];
extern TNimType NTI148023; /* UpdatablePlayer:ObjectType */
extern TNimType NTI148021; /* IUpdatable:ObjectType */
static TNimType* Nim_OfCheck_CACHE3[2];

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = 0;
	{
		if (!(obj == subclass)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!((*obj).base == subclass)) goto LA7;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA7: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA11: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA15: ;
	result = isobjslowpath_23217(obj, subclass, cache);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(void, draw_146107)(IvisibleHEX3Aobjecttype146058* impl) {
	nimfr("draw", "ivisible.nim")
	nimln(18, "ivisible.nim");
	{
		if (!((impl) && ((*impl).Sup.m_type == (&NTI146063)))) goto LA3;
		if (impl) chckObj((*impl).Sup.m_type, (&NTI146063));
		draw_146121(((InvisibleHEX3Aobjecttype146063*) (impl)));
	}
	goto LA1;
	LA3: ;
	{
		if (!((impl) && ((*impl).Sup.m_type == (&NTI146061)))) goto LA6;
		if (impl) chckObj((*impl).Sup.m_type, (&NTI146061));
		draw_146112(((VisiblenormalHEX3Aobjecttype146061*) (impl)));
	}
	goto LA1;
	LA6: ;
	{
		if (!((impl) && (isObjWithCache((*impl).Sup.m_type, (&NTI146058), Nim_OfCheck_CACHE1)))) goto LA9;
		draw_146098(impl);
	}
	goto LA1;
	LA9: ;
	LA1: ;
	popFrame();
}

N_NIMCALL(void, move_146139)(IvisibleHEX3Aobjecttype146058* impl, NI32 x, NI32 y) {
	nimfr("move", "ivisible.nim")
	nimln(27, "ivisible.nim");
	move_146130(impl, x, y);
	popFrame();
}

N_NIMCALL(void, collide_147067)(IcollidableHEX3Aobjecttype147018* impl) {
	nimfr("collide", "icollidable.nim")
	nimln(19, "icollidable.nim");
	{
		if (!((impl) && ((*impl).Sup.m_type == (&NTI147023)))) goto LA3;
		if (impl) chckObj((*impl).Sup.m_type, (&NTI147023));
		collide_147072(((NotcollidableHEX3Aobjecttype147023*) (impl)));
	}
	goto LA1;
	LA3: ;
	{
		if (!((impl) && (isObjWithCache((*impl).Sup.m_type, (&NTI147018), Nim_OfCheck_CACHE2)))) goto LA6;
		collide_147058(impl);
	}
	goto LA1;
	LA6: ;
	LA1: ;
	popFrame();
}

N_NIMCALL(void, move_147110)(IcollidableHEX3Aobjecttype147018* impl, NI32 x, NI32 y) {
	nimfr("move", "icollidable.nim")
	nimln(74, "icollidable.nim");
	move_147083(impl, x, y);
	popFrame();
}

N_NIMCALL(void, update_148062)(IupdatableHEX3Aobjecttype148021* obj, IcollidableHEX3Aobjecttype147018* collisionimpl, IvisibleHEX3Aobjecttype146058* visibleimpl) {
	nimfr("update", "iupdatable.nim")
	nimln(20, "iupdatable.nim");
	{
		if (!((obj) && ((*obj).Sup.m_type == (&NTI148023)))) goto LA3;
		if (obj) chckObj((*obj).Sup.m_type, (&NTI148023));
		update_148067(((UpdatableplayerHEX3Aobjecttype148023*) (obj)), collisionimpl, visibleimpl);
	}
	goto LA1;
	LA3: ;
	{
		if (!((obj) && (isObjWithCache((*obj).Sup.m_type, (&NTI148021), Nim_OfCheck_CACHE3)))) goto LA6;
		update_148051(obj, collisionimpl, visibleimpl);
	}
	goto LA1;
	LA6: ;
	LA1: ;
	popFrame();
}

N_NIMCALL(void, update_148171)(UpdatablebombHEX3Aobjecttype148026* obj) {
	nimfr("update", "iupdatable.nim")
	nimln(47, "iupdatable.nim");
	update_148164(obj);
	popFrame();
}

N_NIMCALL(void, move_149023)(Entityobj149007* obj, NI32 x, NI32 y) {
	nimfr("move", "entity.nim")
	nimln(12, "entity.nim");
	move_149014(obj, x, y);
	popFrame();
}

N_NIMCALL(void, moveto_149037)(Entityobj149007* obj, NI32 x, NI32 y) {
	nimfr("moveTo", "entity.nim")
	nimln(16, "entity.nim");
	moveto_149028(obj, x, y);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_winleanDatInit();
	stdlib_timesDatInit();
	stdlib_mathDatInit();
	stdlib_macrosDatInit();
	stdlib_unsignedDatInit();
	sdl2_sdl2DatInit();
	sdl2_imageDatInit();
	sdl2_ttfDatInit();
	HEX00_enumsDatInit();
	HEX00_boxDatInit();
	HEX00_spriteDatInit();
	HEX00_engineDatInit();
	stdlib_basic2dDatInit();
	HEX00_ivisibleDatInit();
	HEX00_icollidableDatInit();
	HEX00_iupdatableDatInit();
	HEX00_entityDatInit();
	HEX00_inputDatInit();
	HEX00_bombDatInit();
	HEX00_playerDatInit();
	HEX00_wallDatInit();
	HEX00_gameDatInit();
	mainDatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_winleanInit();
	stdlib_timesInit();
	stdlib_mathInit();
	stdlib_macrosInit();
	stdlib_unsignedInit();
	sdl2_sdl2Init();
	sdl2_imageInit();
	sdl2_ttfInit();
	HEX00_enumsInit();
	HEX00_boxInit();
	HEX00_spriteInit();
	HEX00_engineInit();
	stdlib_basic2dInit();
	HEX00_ivisibleInit();
	HEX00_icollidableInit();
	HEX00_iupdatableInit();
	HEX00_entityInit();
	HEX00_inputInit();
	HEX00_bombInit();
	HEX00_playerInit();
	HEX00_wallInit();
	HEX00_gameInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	mainInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, mainInit)(void) {
	NI32 LOC1;
	nimfr("main", "main.nim")
	nimln(7, "main.nim");
	LOC1 = 0;
	LOC1 = Dl_131272(((int) 65535));
	nimln(9, "main.nim");
	randomize_112024();
	nimln(11, "main.nim");
	initgame_154544();
	{
		nimln(13, "main.nim");
		while (1) {
			if (!rungame_154004) goto LA3;
			nimln(14, "main.nim");
			update_154021();
			nimln(15, "main.nim");
			render_154030();
		} LA3: ;
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit)(void) {
}

