/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\sdl2_sdl2.o c:\users\john\documents\nim\bomberman\nimcache\sdl2_sdl2.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct Event121164 Event121164;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct WindowptrHEX3Aobjecttype121574 WindowptrHEX3Aobjecttype121574;
typedef struct RendererptrHEX3Aobjecttype121576 RendererptrHEX3Aobjecttype121576;
typedef struct Color122280 Color122280;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TextureptrHEX3Aobjecttype121578 TextureptrHEX3Aobjecttype121578;
typedef struct Box140009 Box140009;
typedef struct Surface122290 Surface122290;
typedef struct Keyboardeventobj121176 Keyboardeventobj121176;
typedef struct Pixelformat122284 Pixelformat122284;
typedef struct BlitmapptrHEX3Aobjecttype122332 BlitmapptrHEX3Aobjecttype122332;
typedef struct Keysym121270 Keysym121270;
typedef struct Palette122282 Palette122282;
typedef NU8 TY121349[52];
struct  Event121164  {
NI32 kind;
TY121349 padding;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(WindowptrHEX3Aobjecttype121574*, TY132189) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(RendererptrHEX3Aobjecttype121576*, TY131349) (WindowptrHEX3Aobjecttype121574* window, int index, int flags);
typedef N_CDECL_PTR(NCSTRING, TY132713) (void);
struct Color122280 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NI32, TY131623) (RendererptrHEX3Aobjecttype121576* renderer, TextureptrHEX3Aobjecttype121578* texture, Box140009* srcrect, Box140009* dstrect);
typedef N_CDECL_PTR(NI32, TY131033) (RendererptrHEX3Aobjecttype121576* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY131661) (RendererptrHEX3Aobjecttype121576* renderer);
typedef N_CDECL_PTR(void, TY131678) (RendererptrHEX3Aobjecttype121576* renderer);
typedef N_CDECL_PTR(TextureptrHEX3Aobjecttype121578*, TY131386) (RendererptrHEX3Aobjecttype121576* renderer, Surface122290* surface);
typedef N_CDECL_PTR(NI32, TY131404) (TextureptrHEX3Aobjecttype121578* texture, NU32* format, int* access, int* w, int* h);
typedef N_CDECL_PTR(void, TY131726) (Surface122290* surface);
typedef N_CDECL_PTR(void, TY131069) (TextureptrHEX3Aobjecttype121578* texture);
typedef N_CDECL_PTR(NI32, TY132628) (Event121164* event);
typedef N_CDECL_PTR(NU8, TY132500) (int* x, int* y);
typedef N_CDECL_PTR(NI32, TY131273) (int flags);
struct  WindowptrHEX3Aobjecttype121574  {
char dummy;
};
struct  RendererptrHEX3Aobjecttype121576  {
char dummy;
};
struct  TextureptrHEX3Aobjecttype121578  {
char dummy;
};
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  Surface122290  {
NU32 flags;
Pixelformat122284* format;
NI32 w;
NI32 h;
NI32 pitch;
void* pixels;
void* userdata;
NI32 locked;
void* lockdata;
Box140009 cliprect;
BlitmapptrHEX3Aobjecttype122332* map;
int refcount;
};
struct  Keysym121270  {
NI32 scancode;
int sym;
NI16 modstate;
int unicode;
};
struct  Keyboardeventobj121176  {
NI32 kind;
NU32 timestamp;
NU32 windowid;
NU8 state;
NIM_BOOL repeat;
NU8 pad1;
NU8 pad2;
Keysym121270 keysym;
};
typedef NU8 TY122314[2];
struct  Pixelformat122284  {
NU32 format;
Palette122282* palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY122314 padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
Pixelformat122284* next;
};
struct  BlitmapptrHEX3Aobjecttype122332  {
char dummy;
};
struct  Palette122282  {
int ncolors;
Color122280* colors;
NU32 version;
int refcount;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
STRING_LITERAL(TMP312, "SDL2.dll", 8);
STRING_LITERAL(TMP313, "SDL2.dll", 8);
STRING_LITERAL(TMP357, "contains({KeyDown, KeyUp}, event.kind) ", 39);
Event121164 defaultevent_133420;
static void* TMP311;
TY132189 Dl_132188;
TY131349 Dl_131348;
TY132713 Dl_132712;
TNimType NTI122280; /* Color */
extern TNimType NTI120; /* uint8 */
TY131623 Dl_131622;
TY131033 Dl_131032;
TY131661 Dl_131660;
TY131678 Dl_131677;
TY131386 Dl_131385;
TY131404 Dl_131403;
TY131726 Dl_131725;
TY131069 Dl_131068;
extern TFrame* frameptr_17042;
TY132628 Dl_132627;
TY132500 Dl_132499;
TY131273 Dl_131272;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NIM_BOOL, tobool_121657)(NI32 some) {
	NIM_BOOL result;
	nimfr("toBool", "sdl2.nim")
	result = 0;
	nimln(307, "sdl2.nim");
	result = ((NIM_BOOL) (some));
	popFrame();
	return result;
}

N_NIMCALL(Keyboardeventobj121176*, Evkeyboard_122813)(Event121164* event_122810) {
	Keyboardeventobj121176* result;
	nimfr("EvKeyboard", "sdl2.nim")
{	result = 0;
	nimln(589, "sdl2.nim");
	{
		if (!!(((*event_122810).kind == ((NI32) 768) || (*event_122810).kind == ((NI32) 769)))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP357));
	}
	LA3: ;
	nimln(590, "sdl2.nim");
	result = ((Keyboardeventobj121176*) (event_122810));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init)(void) {
	Event121164 LOC1;
	nimfr("sdl2", "sdl2.nim")
	nimln(1723, "sdl2.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.kind = ((NI32) 256);
	defaultevent_133420 = LOC1;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit)(void) {
static TNimNode* TMP318[4];
static TNimNode TMP265[5];
NTI122280.size = sizeof(Color122280);
NTI122280.kind = 18;
NTI122280.base = 0;
NTI122280.flags = 3;
TMP318[0] = &TMP265[1];
TMP265[1].kind = 1;
TMP265[1].offset = offsetof(Color122280, Field0);
TMP265[1].typ = (&NTI120);
TMP265[1].name = "Field0";
TMP318[1] = &TMP265[2];
TMP265[2].kind = 1;
TMP265[2].offset = offsetof(Color122280, Field1);
TMP265[2].typ = (&NTI120);
TMP265[2].name = "Field1";
TMP318[2] = &TMP265[3];
TMP265[3].kind = 1;
TMP265[3].offset = offsetof(Color122280, Field2);
TMP265[3].typ = (&NTI120);
TMP265[3].name = "Field2";
TMP318[3] = &TMP265[4];
TMP265[4].kind = 1;
TMP265[4].offset = offsetof(Color122280, Field3);
TMP265[4].typ = (&NTI120);
TMP265[4].name = "Field3";
TMP265[0].len = 4; TMP265[0].kind = 2; TMP265[0].sons = &TMP318[0];
NTI122280.node = &TMP265[0];
if (!((TMP311 = nimLoadLibrary((NimStringDesc*) &TMP312))
)) nimLoadLibraryError((NimStringDesc*) &TMP313);
	Dl_132188 = (TY132189) nimGetProcAddr(TMP311, "SDL_CreateWindow");
	Dl_131348 = (TY131349) nimGetProcAddr(TMP311, "SDL_CreateRenderer");
	Dl_132712 = (TY132713) nimGetProcAddr(TMP311, "SDL_GetError");
	Dl_131622 = (TY131623) nimGetProcAddr(TMP311, "SDL_RenderCopy");
	Dl_131032 = (TY131033) nimGetProcAddr(TMP311, "SDL_SetRenderDrawColor");
	Dl_131660 = (TY131661) nimGetProcAddr(TMP311, "SDL_RenderClear");
	Dl_131677 = (TY131678) nimGetProcAddr(TMP311, "SDL_RenderPresent");
	Dl_131385 = (TY131386) nimGetProcAddr(TMP311, "SDL_CreateTextureFromSurface");
	Dl_131403 = (TY131404) nimGetProcAddr(TMP311, "SDL_QueryTexture");
	Dl_131725 = (TY131726) nimGetProcAddr(TMP311, "SDL_FreeSurface");
	Dl_131068 = (TY131069) nimGetProcAddr(TMP311, "SDL_DestroyTexture");
	Dl_132627 = (TY132628) nimGetProcAddr(TMP311, "SDL_PollEvent");
	Dl_132499 = (TY132500) nimGetProcAddr(TMP311, "SDL_GetMouseState");
	Dl_131272 = (TY131273) nimGetProcAddr(TMP311, "SDL_Init");
}

