/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\sdl2_ttf.o c:\users\john\documents\nim\bomberman\nimcache\sdl2_ttf.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct FontptrHEX3Aobjecttype137409 FontptrHEX3Aobjecttype137409;
typedef struct Surface122290 Surface122290;
typedef struct Color122280 Color122280;
typedef struct Pixelformat122284 Pixelformat122284;
typedef struct Box140009 Box140009;
typedef struct BlitmapptrHEX3Aobjecttype122332 BlitmapptrHEX3Aobjecttype122332;
typedef struct Palette122282 Palette122282;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, TY137624) (void);
typedef N_CDECL_PTR(FontptrHEX3Aobjecttype137409*, TY137629) (NCSTRING file, int ptsize);
struct Color122280 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
typedef N_CDECL_PTR(Surface122290*, TY137835) (FontptrHEX3Aobjecttype137409* font, NCSTRING text, Color122280 fg);
struct  FontptrHEX3Aobjecttype137409  {
char dummy;
};
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  Surface122290  {
NU32 flags;
Pixelformat122284* format;
NI32 w;
NI32 h;
NI32 pitch;
void* pixels;
void* userdata;
NI32 locked;
void* lockdata;
Box140009 cliprect;
BlitmapptrHEX3Aobjecttype122332* map;
int refcount;
};
typedef NU8 TY122314[2];
struct  Pixelformat122284  {
NU32 format;
Palette122282* palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY122314 padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
Pixelformat122284* next;
};
struct  BlitmapptrHEX3Aobjecttype122332  {
char dummy;
};
struct  Palette122282  {
int ncolors;
Color122280* colors;
NU32 version;
int refcount;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP315, "SDL2_ttf.dll", 12);
STRING_LITERAL(TMP316, "SDL2_ttf.dll", 12);
static void* TMP314;
TY137624 Dl_137623;
TY137629 Dl_137628;
TY137835 Dl_137834;
extern TFrame* frameptr_17042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_ttfInit)(void) {
	nimfr("ttf", "ttf.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_ttfDatInit)(void) {
if (!((TMP314 = nimLoadLibrary((NimStringDesc*) &TMP315))
)) nimLoadLibraryError((NimStringDesc*) &TMP316);
	Dl_137623 = (TY137624) nimGetProcAddr(TMP314, "TTF_Init");
	Dl_137628 = (TY137629) nimGetProcAddr(TMP314, "TTF_OpenFont");
	Dl_137834 = (TY137835) nimGetProcAddr(TMP314, "TTF_RenderText_Solid");
}

