/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\sprite.o c:\users\john\documents\nim\bomberman\nimcache\sprite.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct SpriteHEX3Aobjecttype141009 SpriteHEX3Aobjecttype141009;
typedef struct Box140009 Box140009;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct Box140009 {
NI32 Field0;
NI32 Field1;
NI32 Field2;
NI32 Field3;
};
struct  SpriteHEX3Aobjecttype141009  {
Box140009 box;
NU8 spritetype;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(SpriteHEX3Aobjecttype141009*, newsprite_141016)(NI32 x, NI32 y, NI32 w, NI32 h, NU8 spritetype);
N_NIMCALL(void, TMP307)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, move_141032)(SpriteHEX3Aobjecttype141009* obj, NI32 x, NI32 y);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, moveto_141061)(SpriteHEX3Aobjecttype141009* obj, NI32 x, NI32 y);
N_NIMCALL(Box140009*, getbox_141072)(SpriteHEX3Aobjecttype141009* obj);
N_NIMCALL(NU8, getspritetype_141084)(SpriteHEX3Aobjecttype141009* obj);
TNimType NTI141009; /* Sprite:ObjectType */
extern TNimType NTI140009; /* Box */
extern TNimType NTI139007; /* SpriteE */
TNimType NTI141008; /* Sprite */
extern TFrame* frameptr_17042;
N_NIMCALL(void, TMP307)(void* p, NI op) {
	SpriteHEX3Aobjecttype141009* a;
	a = (SpriteHEX3Aobjecttype141009*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(SpriteHEX3Aobjecttype141009*, newsprite_141016)(NI32 x, NI32 y, NI32 w, NI32 h, NU8 spritetype) {
	SpriteHEX3Aobjecttype141009* result;
	SpriteHEX3Aobjecttype141009* LOC1;
	nimfr("newSprite", "sprite.nim")
	result = 0;
	nimln(12, "sprite.nim");
	LOC1 = 0;
	LOC1 = (SpriteHEX3Aobjecttype141009*) newObj((&NTI141008), sizeof(SpriteHEX3Aobjecttype141009));
	(*LOC1).box.Field0 = x;
	(*LOC1).box.Field1 = y;
	(*LOC1).box.Field2 = w;
	(*LOC1).box.Field3 = h;
	(*LOC1).spritetype = spritetype;
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, move_141032)(SpriteHEX3Aobjecttype141009* obj, NI32 x, NI32 y) {
	NI32 TMP308;
	NI32 TMP309;
	nimfr("move", "sprite.nim")
	nimln(15, "sprite.nim");
	TMP308 = addInt((*obj).box.Field0, x);
	(*obj).box.Field0 = (NI32)(TMP308);
	nimln(16, "sprite.nim");
	TMP309 = addInt((*obj).box.Field1, y);
	(*obj).box.Field1 = (NI32)(TMP309);
	popFrame();
}

N_NIMCALL(void, moveto_141061)(SpriteHEX3Aobjecttype141009* obj, NI32 x, NI32 y) {
	nimfr("moveTo", "sprite.nim")
	nimln(19, "sprite.nim");
	(*obj).box.Field0 = x;
	nimln(20, "sprite.nim");
	(*obj).box.Field1 = y;
	popFrame();
}

N_NIMCALL(Box140009*, getbox_141072)(SpriteHEX3Aobjecttype141009* obj) {
	Box140009* result;
	nimfr("getBox", "sprite.nim")
	result = 0;
	nimln(23, "sprite.nim");
	result = (&(*obj).box);
	popFrame();
	return result;
}

N_NIMCALL(NU8, getspritetype_141084)(SpriteHEX3Aobjecttype141009* obj) {
	NU8 result;
	nimfr("getSpriteType", "sprite.nim")
	result = 0;
	nimln(26, "sprite.nim");
	result = (*obj).spritetype;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_spriteInit)(void) {
	nimfr("sprite", "sprite.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_spriteDatInit)(void) {
static TNimNode* TMP302[2];
static TNimNode TMP294[3];
NTI141009.size = sizeof(SpriteHEX3Aobjecttype141009);
NTI141009.kind = 18;
NTI141009.base = 0;
NTI141009.flags = 3;
TMP302[0] = &TMP294[1];
TMP294[1].kind = 1;
TMP294[1].offset = offsetof(SpriteHEX3Aobjecttype141009, box);
TMP294[1].typ = (&NTI140009);
TMP294[1].name = "box";
TMP302[1] = &TMP294[2];
TMP294[2].kind = 1;
TMP294[2].offset = offsetof(SpriteHEX3Aobjecttype141009, spritetype);
TMP294[2].typ = (&NTI139007);
TMP294[2].name = "spriteType";
TMP294[0].len = 2; TMP294[0].kind = 2; TMP294[0].sons = &TMP302[0];
NTI141009.node = &TMP294[0];
NTI141008.size = sizeof(SpriteHEX3Aobjecttype141009*);
NTI141008.kind = 22;
NTI141008.base = (&NTI141009);
NTI141008.flags = 2;
NTI141008.marker = TMP307;
}

