/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\john\documents\nim\bomberman\nimcache\stdlib_basic2d.o c:\users\john\documents\nim\bomberman\nimcache\stdlib_basic2d.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <math.h>

#include <string.h>
typedef struct Tmatrix2d143043 Tmatrix2d143043;
typedef struct Tpoint2d143045 Tpoint2d143045;
typedef struct Tvector2d143047 Tvector2d143047;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Divbyzeroerror3441 Divbyzeroerror3441;
typedef struct Arithmeticerror3439 Arithmeticerror3439;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  Tmatrix2d143043  {
NF ax;
NF ay;
NF bx;
NF by;
NF tx;
NF ty;
};
struct  Tpoint2d143045  {
NF x;
NF y;
};
struct  Tvector2d143047  {
NF x;
NF y;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Arithmeticerror3439  {
  Exception Sup;
};
struct  Divbyzeroerror3441  {
  Arithmeticerror3439 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef NI TY27820[16];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
N_NIMCALL(NimStringDesc*, rtos_143118)(NF val);
N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, NU8 format, NI precision);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, clamp_143136)(NF x, NF a, NF b);
N_NIMCALL(NF, safearccos_143128)(NF v);
static N_INLINE(void, setelements_143191)(Tmatrix2d143043* t, NF ax, NF ay, NF bx, NF by, NF tx, NF ty);
N_NIMCALL(Tmatrix2d143043, matrix2d_143061)(NF ax, NF ay, NF bx, NF by, NF tx, NF ty);
N_NIMCALL(Tmatrix2d143043, HEX26_143223)(Tmatrix2d143043* a, Tmatrix2d143043* b);
N_NIMCALL(Tmatrix2d143043, scale_143235)(NF s);
N_NIMCALL(Tmatrix2d143043, scale_143250)(NF s, Tpoint2d143045 org);
N_NIMCALL(Tmatrix2d143043, stretch_143264)(NF sx, NF sy);
N_NIMCALL(Tmatrix2d143043, stretch_143280)(NF sx, NF sy, Tpoint2d143045 org);
N_NIMCALL(Tmatrix2d143043, move_143295)(NF dx, NF dy);
N_NIMCALL(Tmatrix2d143043, move_143311)(Tvector2d143047 v);
N_NIMCALL(Tmatrix2d143043, rotate_143326)(NF rad);
N_NIMCALL(Tmatrix2d143043, rotate_143341)(NF rad, Tpoint2d143045 org);
N_NIMCALL(Tmatrix2d143043, mirror_143355)(Tvector2d143047 v);
N_NIMCALL(Tmatrix2d143043, mirror_143379)(Tpoint2d143045 org, Tvector2d143047 v);
N_NIMCALL(Tmatrix2d143043, skew_143402)(NF xskew, NF yskew);
N_NIMCALL(NimStringDesc*, HEX24_143416)(Tmatrix2d143043* t);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NIM_BOOL, isuniform_143426)(Tmatrix2d143043* t, NF tol);
N_NIMCALL(NF, determinant_143438)(Tmatrix2d143043* t);
N_NIMCALL(NIM_BOOL, ismirroring_143448)(Tmatrix2d143043* m);
N_NIMCALL(Tmatrix2d143043, inverse_143459)(Tmatrix2d143043* m);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, equals_143485)(Tmatrix2d143043* m1, Tmatrix2d143043* m2, NF tol);
N_NIMCALL(NIM_BOOL, HEX3DHEX7E_143498)(Tmatrix2d143043* m1, Tmatrix2d143043* m2);
N_NIMCALL(NIM_BOOL, isidentity_143509)(Tmatrix2d143043* m, NF tol);
N_NIMCALL(void, apply_143521)(Tmatrix2d143043* m, NF* x, NF* y, NIM_BOOL translate);
static N_INLINE(Tvector2d143047, vector2d_143072)(NF x, NF y);
N_NIMCALL(Tvector2d143047, polarvector2d_143547)(NF ang, NF len);
N_NIMCALL(Tvector2d143047, slopevector2d_143558)(NF slope, NF len);
static N_INLINE(NF, len_143570)(Tvector2d143047 v);
static N_INLINE(void, HEX2AHEX3D_143593)(NF* x, NF y);
N_NIMCALL(void, lenHEX3D_143580)(Tvector2d143047* v, NF newlen);
static N_INLINE(NF, sqrlen_143623)(Tvector2d143047 v);
N_NIMCALL(NF, angle_143633)(Tvector2d143047 v);
static N_INLINE(void, HEX2BHEX3D_107689)(NF* x, NF y);
N_NIMCALL(NimStringDesc*, HEX24_143654)(Tvector2d143047 v);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(Tvector2d143047, HEX26_143664)(Tvector2d143047 v, Tmatrix2d143043* m);
static N_INLINE(void, HEX26HEX3D_143675)(Tvector2d143047* v, Tmatrix2d143043* m);
N_NIMCALL(NIM_BOOL, trynormalize_143687)(Tvector2d143047* v);
static N_INLINE(void, HEX2FHEX3D_88702)(NF* x, NF y);
static N_INLINE(void, normalize_143702)(Tvector2d143047* v);
N_NIMCALL(void, transformnorm_143725)(Tvector2d143047* v, Tmatrix2d143043* t);
N_NIMCALL(void, transforminv_143752)(Tvector2d143047* v, Tmatrix2d143043* t);
N_NIMCALL(void, transformnorminv_143779)(Tvector2d143047* v, Tmatrix2d143043* t);
static N_INLINE(void, rotate90_143791)(Tvector2d143047* v);
static N_INLINE(void, rotate180_143811)(Tvector2d143047* v);
static N_INLINE(void, rotate270_143821)(Tvector2d143047* v);
N_NIMCALL(void, rotate_143841)(Tvector2d143047* v, NF rad);
static N_INLINE(void, scale_143855)(Tvector2d143047* v, NF fac);
static N_INLINE(void, stretch_143886)(Tvector2d143047* v, NF facx, NF facy);
N_NIMCALL(void, mirror_143918)(Tvector2d143047* v, Tvector2d143047 mirrvec);
N_NIMCALL(Tvector2d143047, HEX2D_143941)(Tvector2d143047 v);
static N_INLINE(Tvector2d143047, HEX2B_143963)(Tvector2d143047 a_143952, Tvector2d143047 b_143954);
static N_INLINE(Tvector2d143047, HEX2B_143969)(Tvector2d143047 a_143956, NF b_143958);
static N_INLINE(Tvector2d143047, HEX2B_143975)(NF a_143960, Tvector2d143047 b_143962);
static N_INLINE(Tvector2d143047, HEX2D_143996)(Tvector2d143047 a_143985, Tvector2d143047 b_143987);
static N_INLINE(Tvector2d143047, HEX2D_144002)(Tvector2d143047 a_143989, NF b_143991);
static N_INLINE(Tvector2d143047, HEX2D_144008)(NF a_143993, Tvector2d143047 b_143995);
static N_INLINE(Tvector2d143047, HEX2A_144029)(Tvector2d143047 a_144018, Tvector2d143047 b_144020);
static N_INLINE(Tvector2d143047, HEX2A_144035)(Tvector2d143047 a_144022, NF b_144024);
static N_INLINE(Tvector2d143047, HEX2A_144041)(NF a_144026, Tvector2d143047 b_144028);
static N_INLINE(Tvector2d143047, HEX2F_144062)(Tvector2d143047 a_144051, Tvector2d143047 b_144053);
static N_INLINE(Tvector2d143047, HEX2F_144068)(Tvector2d143047 a_144055, NF b_144057);
static N_INLINE(Tvector2d143047, HEX2F_144074)(NF a_144059, Tvector2d143047 b_144061);
static N_INLINE(void, HEX2BHEX3D_144091)(Tvector2d143047* a_144084, Tvector2d143047 b_144086);
static N_INLINE(void, HEX2BHEX3D_144117)(Tvector2d143047* a_144088, NF b_144090);
static N_INLINE(void, HEX2DHEX3D_144158)(NF* x, NF y);
static N_INLINE(void, HEX2DHEX3D_144154)(Tvector2d143047* a_144147, Tvector2d143047 b_144149);
static N_INLINE(void, HEX2DHEX3D_144183)(Tvector2d143047* a_144151, NF b_144153);
static N_INLINE(void, HEX2AHEX3D_144220)(Tvector2d143047* a_144213, Tvector2d143047 b_144215);
static N_INLINE(void, HEX2AHEX3D_144246)(Tvector2d143047* a_144217, NF b_144219);
static N_INLINE(void, HEX2FHEX3D_144283)(Tvector2d143047* a_144276, Tvector2d143047 b_144278);
static N_INLINE(void, HEX2FHEX3D_144291)(Tvector2d143047* a_144280, NF b_144282);
N_NIMCALL(NF, dot_144302)(Tvector2d143047 v1, Tvector2d143047 v2);
N_NIMCALL(NF, cross_144313)(Tvector2d143047 v1, Tvector2d143047 v2);
N_NIMCALL(NIM_BOOL, equals_144324)(Tvector2d143047 v1, Tvector2d143047 v2, NF tol);
N_NIMCALL(NIM_BOOL, HEX3DHEX7E_144337)(Tvector2d143047 v1, Tvector2d143047 v2);
N_NIMCALL(NF, angleto_144348)(Tvector2d143047 v1, Tvector2d143047 v2);
N_NIMCALL(NF, angleccw_144364)(Tvector2d143047 v1, Tvector2d143047 v2);
N_NIMCALL(NF, anglecw_144377)(Tvector2d143047 v1, Tvector2d143047 v2);
N_NIMCALL(NF, turnangle_144390)(Tvector2d143047 v1, Tvector2d143047 v2);
N_NIMCALL(Tvector2d143047, bisect_144403)(Tvector2d143047 v1, Tvector2d143047 v2);
static N_INLINE(Tpoint2d143045, point2d_143079)(NF x, NF y);
N_NIMCALL(NF, sqrdist_144440)(Tpoint2d143045 a, Tpoint2d143045 b);
static N_INLINE(NF, dist_144453)(Tpoint2d143045 a, Tpoint2d143045 b);
N_NIMCALL(NF, angle_144464)(Tpoint2d143045 a, Tpoint2d143045 b);
N_NIMCALL(NimStringDesc*, HEX24_144489)(Tpoint2d143045 p);
static N_INLINE(Tpoint2d143045, HEX26_144499)(Tpoint2d143045 p, Tmatrix2d143043* t);
static N_INLINE(void, HEX26HEX3D_144510)(Tpoint2d143045* p, Tmatrix2d143043* t);
static N_INLINE(void, transforminv_144522)(Tpoint2d143045* p, Tmatrix2d143043* t);
static N_INLINE(Tpoint2d143045, HEX2B_144549)(Tpoint2d143045 p, Tvector2d143047 v);
static N_INLINE(void, HEX2BHEX3D_144560)(Tpoint2d143045* p, Tvector2d143047 v);
static N_INLINE(Tpoint2d143045, HEX2D_144591)(Tpoint2d143045 p, Tvector2d143047 v);
static N_INLINE(Tvector2d143047, HEX2D_144602)(Tpoint2d143045 p1, Tpoint2d143045 p2);
static N_INLINE(void, HEX2DHEX3D_144613)(Tpoint2d143045* p, Tvector2d143047 v);
static N_INLINE(NIM_BOOL, equals_144644)(Tpoint2d143045 p1, Tpoint2d143045 p2, NF tol);
static N_INLINE(NIM_BOOL, HEX3DHEX7E_144657)(Tpoint2d143045 p1, Tpoint2d143045 p2);
N_NIMCALL(Tpoint2d143045, polar_144668)(Tpoint2d143045 p, NF ang, NF dist);
N_NIMCALL(void, rotate_144680)(Tpoint2d143045* p, NF rad);
N_NIMCALL(void, rotate_144694)(Tpoint2d143045* p, NF rad, Tpoint2d143045 org);
static N_INLINE(void, scale_144709)(Tpoint2d143045* p, NF fac);
static N_INLINE(void, scale_144740)(Tpoint2d143045* p, NF fac, Tpoint2d143045 org);
static N_INLINE(void, stretch_144752)(Tpoint2d143045* p, NF facx, NF facy);
static N_INLINE(void, stretch_144784)(Tpoint2d143045* p, NF facx, NF facy, Tpoint2d143045 org);
static N_INLINE(void, move_144797)(Tpoint2d143045* p, NF dx, NF dy);
static N_INLINE(void, move_144829)(Tpoint2d143045* p, Tvector2d143047 v);
N_NIMCALL(NF, sgnarea_144860)(Tpoint2d143045 a, Tpoint2d143045 b, Tpoint2d143045 c);
N_NIMCALL(NF, area_144873)(Tpoint2d143045 a, Tpoint2d143045 b, Tpoint2d143045 c);
N_NIMCALL(Tpoint2d143045, closestpoint_144885)(Tpoint2d143045 p, Tpoint2d143045* pts, NI ptsLen0);
N_NIMCALL(void, failedassertimpl_88817)(NimStringDesc* msg);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NF, normangle_145039)(NF ang);
N_NIMCALL(NF, mod_112807)(NF x, NF y);
static N_INLINE(NF, degtorad_145050)(NF deg);
static N_INLINE(NF, radtodeg_145060)(NF rad);
STRING_LITERAL(TMP328, ",", 1);
STRING_LITERAL(TMP329, "Cannot invert a zero determinant matrix", 39);
STRING_LITERAL(TMP330, "Cannot normalize zero length vector", 35);
STRING_LITERAL(TMP331, "Matrix is not invertible", 24);
STRING_LITERAL(TMP332, "0 < len(pts) ", 13);
Tmatrix2d143043 Idmatrix_143092;
Tpoint2d143045 Origo_143095;
Tvector2d143047 Xaxis_143098;
Tvector2d143047 Yaxis_143101;
extern TFrame* frameptr_17042;
extern TNimType NTI23601; /* ref DivByZeroError */
extern TNimType NTI3441; /* DivByZeroError */
extern Tgcheap48616 gch_48644;
TNimType NTI143047; /* TVector2d */
extern TNimType NTI128; /* float */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NimStringDesc*, rtos_143118)(NF val) {
	NimStringDesc* result;
	nimfr("rtos", "basic2d.nim")
{	result = 0;
	nimln(108, "basic2d.nim");
	result = nsuformatFloat(val, ((NU8) 0), ((NI) 0));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, safearccos_143128)(NF v) {
	NF result;
	NF LOC1;
	nimfr("safeArccos", "basic2d.nim")
{	result = 0;
	nimln(114, "basic2d.nim");
	LOC1 = 0;
	LOC1 = clamp_143136(v, -1.0000000000000000e+000, 1.0000000000000000e+000);
	result = acos(LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, setelements_143191)(Tmatrix2d143043* t, NF ax, NF ay, NF bx, NF by, NF tx, NF ty) {
	nimfr("setElements", "basic2d.nim")
	nimln(135, "basic2d.nim");
	(*t).ax = ax;
	nimln(136, "basic2d.nim");
	(*t).ay = ay;
	nimln(137, "basic2d.nim");
	(*t).bx = bx;
	nimln(138, "basic2d.nim");
	(*t).by = by;
	nimln(139, "basic2d.nim");
	(*t).tx = tx;
	nimln(140, "basic2d.nim");
	(*t).ty = ty;
	popFrame();
}

N_NIMCALL(Tmatrix2d143043, matrix2d_143061)(NF ax, NF ay, NF bx, NF by, NF tx, NF ty) {
	Tmatrix2d143043 result;
	nimfr("matrix2d", "basic2d.nim")
	nimln(143, "basic2d.nim");
	setelements_143191((&result), ax, ay, bx, by, tx, ty);
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, HEX26_143223)(Tmatrix2d143043* a, Tmatrix2d143043* b) {
	Tmatrix2d143043 result;
	nimfr("&", "basic2d.nim")
	nimln(151, "basic2d.nim");
	nimln(152, "basic2d.nim");
	nimln(153, "basic2d.nim");
	nimln(154, "basic2d.nim");
	nimln(155, "basic2d.nim");
	nimln(156, "basic2d.nim");
	nimln(157, "basic2d.nim");
	setelements_143191((&result), ((NF)(((NF)((*a).ax) * (NF)((*b).ax))) + (NF)(((NF)((*a).ay) * (NF)((*b).bx)))), ((NF)(((NF)((*a).ax) * (NF)((*b).ay))) + (NF)(((NF)((*a).ay) * (NF)((*b).by)))), ((NF)(((NF)((*a).bx) * (NF)((*b).ax))) + (NF)(((NF)((*a).by) * (NF)((*b).bx)))), ((NF)(((NF)((*a).bx) * (NF)((*b).ay))) + (NF)(((NF)((*a).by) * (NF)((*b).by)))), ((NF)(((NF)(((NF)((*a).tx) * (NF)((*b).ax))) + (NF)(((NF)((*a).ty) * (NF)((*b).bx))))) + (NF)((*b).tx)), ((NF)(((NF)(((NF)((*a).tx) * (NF)((*b).ay))) + (NF)(((NF)((*a).ty) * (NF)((*b).by))))) + (NF)((*b).ty)));
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, scale_143235)(NF s) {
	Tmatrix2d143043 result;
	nimfr("scale", "basic2d.nim")
	nimln(162, "basic2d.nim");
	setelements_143191((&result), s, 0.0, 0.0, s, 0.0, 0.0);
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, scale_143250)(NF s, Tpoint2d143045 org) {
	Tmatrix2d143043 result;
	nimfr("scale", "basic2d.nim")
	nimln(166, "basic2d.nim");
	setelements_143191((&result), s, 0.0, 0.0, s, ((NF)(org.x) - (NF)(((NF)(s) * (NF)(org.x)))), ((NF)(org.y) - (NF)(((NF)(s) * (NF)(org.y)))));
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, stretch_143264)(NF sx, NF sy) {
	Tmatrix2d143043 result;
	nimfr("stretch", "basic2d.nim")
	nimln(171, "basic2d.nim");
	setelements_143191((&result), sx, 0.0, 0.0, sy, 0.0, 0.0);
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, stretch_143280)(NF sx, NF sy, Tpoint2d143045 org) {
	Tmatrix2d143043 result;
	nimfr("stretch", "basic2d.nim")
	nimln(177, "basic2d.nim");
	setelements_143191((&result), sx, 0.0, 0.0, sy, ((NF)(org.x) - (NF)(((NF)(sx) * (NF)(org.x)))), ((NF)(org.y) - (NF)(((NF)(sy) * (NF)(org.y)))));
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, move_143295)(NF dx, NF dy) {
	Tmatrix2d143043 result;
	nimfr("move", "basic2d.nim")
	nimln(181, "basic2d.nim");
	setelements_143191((&result), 1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000, dx, dy);
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, move_143311)(Tvector2d143047 v) {
	Tmatrix2d143043 result;
	nimfr("move", "basic2d.nim")
	nimln(185, "basic2d.nim");
	setelements_143191((&result), 1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000, v.x, v.y);
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, rotate_143326)(NF rad) {
	Tmatrix2d143043 result;
	NF s;
	NF c;
	nimfr("rotate", "basic2d.nim")
	nimln(191, "basic2d.nim");
	s = sin(rad);
	nimln(192, "basic2d.nim");
	c = cos(rad);
	nimln(193, "basic2d.nim");
	setelements_143191((&result), c, s, -(s), c, 0.0, 0.0);
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, rotate_143341)(NF rad, Tpoint2d143045 org) {
	Tmatrix2d143043 result;
	NF s;
	NF c;
	nimfr("rotate", "basic2d.nim")
	nimln(200, "basic2d.nim");
	s = sin(rad);
	nimln(201, "basic2d.nim");
	c = cos(rad);
	nimln(202, "basic2d.nim");
	setelements_143191((&result), c, s, -(s), c, ((NF)(((NF)(org.x) + (NF)(((NF)(s) * (NF)(org.y))))) - (NF)(((NF)(c) * (NF)(org.x)))), ((NF)(((NF)(org.y) - (NF)(((NF)(c) * (NF)(org.y))))) - (NF)(((NF)(s) * (NF)(org.x)))));
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, mirror_143355)(Tvector2d143047 v) {
	Tmatrix2d143043 result;
	NF sqx;
	NF sqy;
	NF nd;
	NF xy2;
	NF sqd;
	nimfr("mirror", "basic2d.nim")
{	nimln(209, "basic2d.nim");
	sqx = ((NF)(v.x) * (NF)(v.x));
	nimln(210, "basic2d.nim");
	sqy = ((NF)(v.y) * (NF)(v.y));
	nimln(211, "basic2d.nim");
	nd = ((NF)(1.0000000000000000e+000) / (NF)(((NF)(sqx) + (NF)(sqy))));
	nimln(212, "basic2d.nim");
	xy2 = ((NF)(((NF)(((NF)(v.x) * (NF)(v.y))) * (NF)(2.0000000000000000e+000))) * (NF)(nd));
	nimln(213, "basic2d.nim");
	sqd = ((NF)(nd) * (NF)(((NF)(sqx) - (NF)(sqy))));
	nimln(215, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (nd == INF);
		if (LOC3) goto LA4;
		LOC3 = (nd == -INF);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(216, "basic2d.nim");
		result = Idmatrix_143092;
		goto BeforeRet;
	}
	LA5: ;
	nimln(218, "basic2d.nim");
	nimln(220, "basic2d.nim");
	setelements_143191((&result), sqd, xy2, xy2, -(sqd), 0.0, 0.0);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, mirror_143379)(Tpoint2d143045 org, Tvector2d143047 v) {
	Tmatrix2d143043 result;
	NF sqx;
	NF sqy;
	NF nd;
	NF xy2;
	NF sqd;
	nimfr("mirror", "basic2d.nim")
{	nimln(228, "basic2d.nim");
	sqx = ((NF)(v.x) * (NF)(v.x));
	nimln(229, "basic2d.nim");
	sqy = ((NF)(v.y) * (NF)(v.y));
	nimln(230, "basic2d.nim");
	nd = ((NF)(1.0000000000000000e+000) / (NF)(((NF)(sqx) + (NF)(sqy))));
	nimln(231, "basic2d.nim");
	xy2 = ((NF)(((NF)(((NF)(v.x) * (NF)(v.y))) * (NF)(2.0000000000000000e+000))) * (NF)(nd));
	nimln(232, "basic2d.nim");
	sqd = ((NF)(nd) * (NF)(((NF)(sqx) - (NF)(sqy))));
	nimln(234, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (nd == INF);
		if (LOC3) goto LA4;
		LOC3 = (nd == -INF);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(235, "basic2d.nim");
		result = Idmatrix_143092;
		goto BeforeRet;
	}
	LA5: ;
	nimln(237, "basic2d.nim");
	nimln(239, "basic2d.nim");
	nimln(240, "basic2d.nim");
	setelements_143191((&result), sqd, xy2, xy2, -(sqd), ((NF)(((NF)(org.x) - (NF)(((NF)(org.y) * (NF)(xy2))))) - (NF)(((NF)(org.x) * (NF)(sqd)))), ((NF)(((NF)(org.y) - (NF)(((NF)(org.x) * (NF)(xy2))))) + (NF)(((NF)(org.y) * (NF)(sqd)))));
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Tmatrix2d143043, skew_143402)(NF xskew, NF yskew) {
	Tmatrix2d143043 result;
	NF LOC1;
	NF LOC2;
	NF LOC3;
	NF LOC4;
	nimfr("skew", "basic2d.nim")
	nimln(248, "basic2d.nim");
	LOC1 = 0;
	LOC1 = cos(yskew);
	LOC2 = 0;
	LOC2 = sin(yskew);
	LOC3 = 0;
	LOC3 = sin(xskew);
	LOC4 = 0;
	LOC4 = cos(xskew);
	setelements_143191((&result), LOC1, LOC2, -(LOC3), LOC4, 0.0, 0.0);
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_143416)(Tmatrix2d143043* t) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	NimStringDesc* LOC6;
	NimStringDesc* LOC7;
	nimfr("$", "basic2d.nim")
{	nimln(253, "basic2d.nim");
	nimln(255, "basic2d.nim");
	LOC1 = 0;
	nimln(253, "basic2d.nim");
	LOC2 = 0;
	LOC2 = rtos_143118((*t).ax);
	LOC3 = 0;
	LOC3 = rtos_143118((*t).ay);
	nimln(254, "basic2d.nim");
	LOC4 = 0;
	LOC4 = rtos_143118((*t).bx);
	LOC5 = 0;
	LOC5 = rtos_143118((*t).by);
	nimln(255, "basic2d.nim");
	LOC6 = 0;
	LOC6 = rtos_143118((*t).tx);
	LOC7 = 0;
	LOC7 = rtos_143118((*t).ty);
	LOC1 = rawNewString(LOC2->Sup.len + LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + LOC6->Sup.len + LOC7->Sup.len + 5);
appendString(LOC1, LOC2);
appendString(LOC1, ((NimStringDesc*) &TMP328));
appendString(LOC1, LOC3);
appendString(LOC1, ((NimStringDesc*) &TMP328));
appendString(LOC1, LOC4);
appendString(LOC1, ((NimStringDesc*) &TMP328));
appendString(LOC1, LOC5);
appendString(LOC1, ((NimStringDesc*) &TMP328));
appendString(LOC1, LOC6);
appendString(LOC1, ((NimStringDesc*) &TMP328));
appendString(LOC1, LOC7);
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isuniform_143426)(Tmatrix2d143043* t, NF tol) {
	NIM_BOOL result;
	nimfr("isUniform", "basic2d.nim")
{	result = 0;
	nimln(265, "basic2d.nim");
	{
		if (!((((NF)(((NF)((*t).ax) * (NF)((*t).bx))) + (NF)(((NF)((*t).ay) * (NF)((*t).by)))) > 0? (((NF)(((NF)((*t).ax) * (NF)((*t).bx))) + (NF)(((NF)((*t).ay) * (NF)((*t).by))))) : -(((NF)(((NF)((*t).ax) * (NF)((*t).bx))) + (NF)(((NF)((*t).ay) * (NF)((*t).by)))))) <= tol)) goto LA3;
		nimln(267, "basic2d.nim");
		{
			if (!((((NF)(((NF)(((NF)((*t).ax) * (NF)((*t).ax))) + (NF)(((NF)((*t).ay) * (NF)((*t).ay))))) - (NF)(((NF)(((NF)((*t).bx) * (NF)((*t).bx))) + (NF)(((NF)((*t).by) * (NF)((*t).by)))))) > 0? (((NF)(((NF)(((NF)((*t).ax) * (NF)((*t).ax))) + (NF)(((NF)((*t).ay) * (NF)((*t).ay))))) - (NF)(((NF)(((NF)((*t).bx) * (NF)((*t).bx))) + (NF)(((NF)((*t).by) * (NF)((*t).by))))))) : -(((NF)(((NF)(((NF)((*t).ax) * (NF)((*t).ax))) + (NF)(((NF)((*t).ay) * (NF)((*t).ay))))) - (NF)(((NF)(((NF)((*t).bx) * (NF)((*t).bx))) + (NF)(((NF)((*t).by) * (NF)((*t).by)))))))) <= tol)) goto LA7;
			nimln(268, "basic2d.nim");
			result = NIM_TRUE;
			goto BeforeRet;
		}
		LA7: ;
	}
	LA3: ;
	nimln(269, "basic2d.nim");
	result = NIM_FALSE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, determinant_143438)(Tmatrix2d143043* t) {
	NF result;
	nimfr("determinant", "basic2d.nim")
{	result = 0;
	nimln(275, "basic2d.nim");
	result = ((NF)(((NF)((*t).ax) * (NF)((*t).by))) - (NF)(((NF)((*t).bx) * (NF)((*t).ay))));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ismirroring_143448)(Tmatrix2d143043* m) {
	NIM_BOOL result;
	NF LOC1;
	nimfr("isMirroring", "basic2d.nim")
{	result = 0;
	nimln(280, "basic2d.nim");
	LOC1 = 0;
	LOC1 = determinant_143438(m);
	result = (LOC1 < 0.0);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Tmatrix2d143043, inverse_143459)(Tmatrix2d143043* m) {
	Tmatrix2d143043 result;
	NF d;
	nimfr("inverse", "basic2d.nim")
	nimln(286, "basic2d.nim");
	d = determinant_143438(m);
	nimln(287, "basic2d.nim");
	{
		Divbyzeroerror3441* e_143467;
		NimStringDesc* LOC5;
		if (!(d == 0.0)) goto LA3;
		e_143467 = 0;
		nimln(2265, "system.nim");
		e_143467 = (Divbyzeroerror3441*) newObj((&NTI23601), sizeof(Divbyzeroerror3441));
		(*e_143467).Sup.Sup.Sup.m_type = (&NTI3441);
		nimln(2266, "system.nim");
		LOC5 = 0;
		LOC5 = (*e_143467).Sup.Sup.message; (*e_143467).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP329));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(288, "basic2d.nim");
		raiseException((Exception*)e_143467, "DivByZeroError");
	}
	LA3: ;
	nimln(290, "basic2d.nim");
	nimln(291, "basic2d.nim");
	nimln(292, "basic2d.nim");
	nimln(293, "basic2d.nim");
	nimln(294, "basic2d.nim");
	setelements_143191((&result), ((NF)((*m).by) / (NF)(d)), ((NF)(-((*m).ay)) / (NF)(d)), ((NF)(-((*m).bx)) / (NF)(d)), ((NF)((*m).ax) / (NF)(d)), ((NF)(((NF)(((NF)((*m).bx) * (NF)((*m).ty))) - (NF)(((NF)((*m).by) * (NF)((*m).tx))))) / (NF)(d)), ((NF)(((NF)(((NF)((*m).ay) * (NF)((*m).tx))) - (NF)(((NF)((*m).ax) * (NF)((*m).ty))))) / (NF)(d)));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, equals_143485)(Tmatrix2d143043* m1, Tmatrix2d143043* m2, NF tol) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NIM_BOOL LOC3;
	NIM_BOOL LOC4;
	NIM_BOOL LOC5;
	nimfr("equals", "basic2d.nim")
{	result = 0;
	nimln(299, "basic2d.nim");
	nimln(304, "basic2d.nim");
	LOC1 = 0;
	nimln(303, "basic2d.nim");
	LOC2 = 0;
	nimln(302, "basic2d.nim");
	LOC3 = 0;
	nimln(301, "basic2d.nim");
	LOC4 = 0;
	nimln(300, "basic2d.nim");
	LOC5 = 0;
	LOC5 = ((((NF)((*m1).ax) - (NF)((*m2).ax)) > 0? (((NF)((*m1).ax) - (NF)((*m2).ax))) : -(((NF)((*m1).ax) - (NF)((*m2).ax)))) <= tol);
	if (!(LOC5)) goto LA6;
	nimln(301, "basic2d.nim");
	LOC5 = ((((NF)((*m1).ay) - (NF)((*m2).ay)) > 0? (((NF)((*m1).ay) - (NF)((*m2).ay))) : -(((NF)((*m1).ay) - (NF)((*m2).ay)))) <= tol);
	LA6: ;
	LOC4 = LOC5;
	if (!(LOC4)) goto LA7;
	nimln(302, "basic2d.nim");
	LOC4 = ((((NF)((*m1).bx) - (NF)((*m2).bx)) > 0? (((NF)((*m1).bx) - (NF)((*m2).bx))) : -(((NF)((*m1).bx) - (NF)((*m2).bx)))) <= tol);
	LA7: ;
	LOC3 = LOC4;
	if (!(LOC3)) goto LA8;
	nimln(303, "basic2d.nim");
	LOC3 = ((((NF)((*m1).by) - (NF)((*m2).by)) > 0? (((NF)((*m1).by) - (NF)((*m2).by))) : -(((NF)((*m1).by) - (NF)((*m2).by)))) <= tol);
	LA8: ;
	LOC2 = LOC3;
	if (!(LOC2)) goto LA9;
	nimln(304, "basic2d.nim");
	LOC2 = ((((NF)((*m1).tx) - (NF)((*m2).tx)) > 0? (((NF)((*m1).tx) - (NF)((*m2).tx))) : -(((NF)((*m1).tx) - (NF)((*m2).tx)))) <= tol);
	LA9: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA10;
	nimln(305, "basic2d.nim");
	LOC1 = ((((NF)((*m1).ty) - (NF)((*m2).ty)) > 0? (((NF)((*m1).ty) - (NF)((*m2).ty))) : -(((NF)((*m1).ty) - (NF)((*m2).ty)))) <= tol);
	LA10: ;
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX7E_143498)(Tmatrix2d143043* m1, Tmatrix2d143043* m2) {
	NIM_BOOL result;
	nimfr("=~", "basic2d.nim")
	result = 0;
	nimln(308, "basic2d.nim");
	nimln(310, "basic2d.nim");
	result = equals_143485(m1, m2, 9.9999999999999995e-007);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isidentity_143509)(Tmatrix2d143043* m, NF tol) {
	NIM_BOOL result;
	nimfr("isIdentity", "basic2d.nim")
{	result = 0;
	nimln(315, "basic2d.nim");
	result = equals_143485(m, (&Idmatrix_143092), tol);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, apply_143521)(Tmatrix2d143043* m, NF* x, NF* y, NIM_BOOL translate) {
	nimfr("apply", "basic2d.nim")
	nimln(320, "basic2d.nim");
	{
		NF newx;
		if (!translate) goto LA3;
		nimln(321, "basic2d.nim");
		newx = ((NF)(((NF)(((NF)((*x)) * (NF)((*m).ax))) + (NF)(((NF)((*y)) * (NF)((*m).bx))))) + (NF)((*m).tx));
		nimln(322, "basic2d.nim");
		(*y) = ((NF)(((NF)(((NF)((*x)) * (NF)((*m).ay))) + (NF)(((NF)((*y)) * (NF)((*m).by))))) + (NF)((*m).ty));
		nimln(323, "basic2d.nim");
		(*x) = newx;
	}
	goto LA1;
	LA3: ;
	{
		NF newx;
		nimln(325, "basic2d.nim");
		newx = ((NF)(((NF)((*x)) * (NF)((*m).ax))) + (NF)(((NF)((*y)) * (NF)((*m).bx))));
		nimln(326, "basic2d.nim");
		(*y) = ((NF)(((NF)((*x)) * (NF)((*m).ay))) + (NF)(((NF)((*y)) * (NF)((*m).by))));
		nimln(327, "basic2d.nim");
		(*x) = newx;
	}
	LA1: ;
	popFrame();
}

static N_INLINE(Tvector2d143047, vector2d_143072)(NF x, NF y) {
	Tvector2d143047 result;
	nimfr("vector2d", "basic2d.nim")
	nimln(335, "basic2d.nim");
	result.x = x;
	nimln(336, "basic2d.nim");
	result.y = y;
	popFrame();
	return result;
}

N_NIMCALL(Tvector2d143047, polarvector2d_143547)(NF ang, NF len) {
	Tvector2d143047 result;
	NF LOC1;
	NF LOC2;
	nimfr("polarVector2d", "basic2d.nim")
	nimln(340, "basic2d.nim");
	LOC1 = 0;
	LOC1 = cos(ang);
	result.x = ((NF)(LOC1) * (NF)(len));
	nimln(341, "basic2d.nim");
	LOC2 = 0;
	LOC2 = sin(ang);
	result.y = ((NF)(LOC2) * (NF)(len));
	popFrame();
	return result;
}

N_NIMCALL(Tvector2d143047, slopevector2d_143558)(NF slope, NF len) {
	Tvector2d143047 result;
	NF ang;
	NF LOC1;
	NF LOC2;
	nimfr("slopeVector2d", "basic2d.nim")
	nimln(346, "basic2d.nim");
	ang = atan(slope);
	nimln(347, "basic2d.nim");
	LOC1 = 0;
	LOC1 = cos(ang);
	result.x = ((NF)(LOC1) * (NF)(len));
	nimln(348, "basic2d.nim");
	LOC2 = 0;
	LOC2 = sin(ang);
	result.y = ((NF)(LOC2) * (NF)(len));
	popFrame();
	return result;
}

static N_INLINE(NF, len_143570)(Tvector2d143047 v) {
	NF result;
	nimfr("len", "basic2d.nim")
	result = 0;
	nimln(351, "basic2d.nim");
	nimln(352, "basic2d.nim");
	result = sqrt(((NF)(((NF)(v.x) * (NF)(v.x))) + (NF)(((NF)(v.y) * (NF)(v.y)))));
	popFrame();
	return result;
}

static N_INLINE(void, HEX2AHEX3D_143593)(NF* x, NF y) {
	nimfr("*=", "system.nim")
	nimln(3000, "system.nim");
	(*x) = ((NF)((*x)) * (NF)(y));
	popFrame();
}

N_NIMCALL(void, lenHEX3D_143580)(Tvector2d143047* v, NF newlen) {
	NF fac;
	NF LOC1;
	nimfr("len=", "basic2d.nim")
{	nimln(356, "basic2d.nim");
	LOC1 = 0;
	LOC1 = len_143570((*v));
	fac = ((NF)(newlen) / (NF)(LOC1));
	nimln(358, "basic2d.nim");
	{
		if (!(newlen == 0.0)) goto LA4;
		nimln(359, "basic2d.nim");
		(*v).x = 0.0;
		nimln(360, "basic2d.nim");
		(*v).y = 0.0;
		nimln(361, "basic2d.nim");
		goto BeforeRet;
	}
	LA4: ;
	nimln(363, "basic2d.nim");
	{
		NIM_BOOL LOC8;
		LOC8 = 0;
		LOC8 = (fac == INF);
		if (LOC8) goto LA9;
		LOC8 = (fac == -INF);
		LA9: ;
		if (!LOC8) goto LA10;
		nimln(366, "basic2d.nim");
		(*v).x = newlen;
		nimln(367, "basic2d.nim");
		(*v).y = 0.0;
	}
	goto LA6;
	LA10: ;
	{
		nimln(369, "basic2d.nim");
		HEX2AHEX3D_143593((&(*v).x), fac);
		nimln(370, "basic2d.nim");
		HEX2AHEX3D_143593((&(*v).y), fac);
	}
	LA6: ;
	}BeforeRet: ;
	popFrame();
}

static N_INLINE(NF, sqrlen_143623)(Tvector2d143047 v) {
	NF result;
	nimfr("sqrLen", "basic2d.nim")
	result = 0;
	nimln(373, "basic2d.nim");
	nimln(375, "basic2d.nim");
	result = ((NF)(((NF)(v.x) * (NF)(v.x))) + (NF)(((NF)(v.y) * (NF)(v.y))));
	popFrame();
	return result;
}

static N_INLINE(void, HEX2BHEX3D_107689)(NF* x, NF y) {
	nimfr("+=", "system.nim")
	nimln(2992, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

N_NIMCALL(NF, angle_143633)(Tvector2d143047 v) {
	NF result;
	nimfr("angle", "basic2d.nim")
	result = 0;
	nimln(380, "basic2d.nim");
	result = atan2(v.y, v.x);
	nimln(381, "basic2d.nim");
	{
		if (!(result < 0.0)) goto LA3;
		HEX2BHEX3D_107689((&result), 6.2831853071795862e+000);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_143654)(Tvector2d143047 v) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	nimfr("$", "basic2d.nim")
	result = 0;
	nimln(385, "basic2d.nim");
	result = rtos_143118(v.x);
	nimln(386, "basic2d.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP328));
	nimln(387, "basic2d.nim");
	LOC1 = 0;
	LOC1 = rtos_143118(v.y);
	result = resizeString(result, LOC1->Sup.len + 0);
appendString(result, LOC1);
	popFrame();
	return result;
}

N_NIMCALL(Tvector2d143047, HEX26_143664)(Tvector2d143047 v, Tmatrix2d143043* m) {
	Tvector2d143047 result;
	nimfr("&", "basic2d.nim")
	nimln(398, "basic2d.nim");
	result.x = ((NF)(((NF)(v.x) * (NF)((*m).ax))) + (NF)(((NF)(v.y) * (NF)((*m).bx))));
	nimln(399, "basic2d.nim");
	result.y = ((NF)(((NF)(v.x) * (NF)((*m).ay))) + (NF)(((NF)(v.y) * (NF)((*m).by))));
	popFrame();
	return result;
}

static N_INLINE(void, HEX26HEX3D_143675)(Tvector2d143047* v, Tmatrix2d143043* m) {
	NF newx;
	nimfr("&=", "basic2d.nim")
	nimln(410, "basic2d.nim");
	newx = ((NF)(((NF)((*v).x) * (NF)((*m).ax))) + (NF)(((NF)((*v).y) * (NF)((*m).bx))));
	nimln(411, "basic2d.nim");
	(*v).y = ((NF)(((NF)((*v).x) * (NF)((*m).ay))) + (NF)(((NF)((*v).y) * (NF)((*m).by))));
	nimln(412, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

static N_INLINE(void, HEX2FHEX3D_88702)(NF* x, NF y) {
	nimfr("/=", "system.nim")
	nimln(3004, "system.nim");
	(*x) = ((NF)((*x)) / (NF)(y));
	popFrame();
}

N_NIMCALL(NIM_BOOL, trynormalize_143687)(Tvector2d143047* v) {
	NIM_BOOL result;
	NF mag;
	nimfr("tryNormalize", "basic2d.nim")
{	result = 0;
	nimln(420, "basic2d.nim");
	mag = len_143570((*v));
	nimln(422, "basic2d.nim");
	{
		if (!(mag == 0.0)) goto LA3;
		nimln(423, "basic2d.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA3: ;
	nimln(425, "basic2d.nim");
	HEX2FHEX3D_88702((&(*v).x), mag);
	nimln(426, "basic2d.nim");
	HEX2FHEX3D_88702((&(*v).y), mag);
	nimln(427, "basic2d.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, normalize_143702)(Tvector2d143047* v) {
	nimfr("normalize", "basic2d.nim")
	nimln(433, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		Divbyzeroerror3441* e_143708;
		NimStringDesc* LOC6;
		LOC3 = 0;
		LOC3 = trynormalize_143687(v);
		if (!!(LOC3)) goto LA4;
		e_143708 = 0;
		nimln(2265, "system.nim");
		e_143708 = (Divbyzeroerror3441*) newObj((&NTI23601), sizeof(Divbyzeroerror3441));
		(*e_143708).Sup.Sup.Sup.m_type = (&NTI3441);
		nimln(2266, "system.nim");
		LOC6 = 0;
		LOC6 = (*e_143708).Sup.Sup.message; (*e_143708).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP330));
		if (LOC6) nimGCunrefNoCycle(LOC6);
		nimln(434, "basic2d.nim");
		raiseException((Exception*)e_143708, "DivByZeroError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, transformnorm_143725)(Tvector2d143047* v, Tmatrix2d143043* t) {
	NF d;
	NF newx;
	nimfr("transformNorm", "basic2d.nim")
	nimln(448, "basic2d.nim");
	d = determinant_143438(t);
	nimln(449, "basic2d.nim");
	{
		Divbyzeroerror3441* e_143734;
		NimStringDesc* LOC5;
		if (!(d == 0.0)) goto LA3;
		e_143734 = 0;
		nimln(2265, "system.nim");
		e_143734 = (Divbyzeroerror3441*) newObj((&NTI23601), sizeof(Divbyzeroerror3441));
		(*e_143734).Sup.Sup.Sup.m_type = (&NTI3441);
		nimln(2266, "system.nim");
		LOC5 = 0;
		LOC5 = (*e_143734).Sup.Sup.message; (*e_143734).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP331));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(450, "basic2d.nim");
		raiseException((Exception*)e_143734, "DivByZeroError");
	}
	LA3: ;
	nimln(451, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)((*t).by) * (NF)((*v).x))) - (NF)(((NF)((*t).ay) * (NF)((*v).y))))) / (NF)(d));
	nimln(452, "basic2d.nim");
	(*v).y = ((NF)(((NF)(((NF)((*t).ax) * (NF)((*v).y))) - (NF)(((NF)((*t).bx) * (NF)((*v).x))))) / (NF)(d));
	nimln(453, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

N_NIMCALL(void, transforminv_143752)(Tvector2d143047* v, Tmatrix2d143043* t) {
	NF d;
	NF newx;
	nimfr("transformInv", "basic2d.nim")
	nimln(461, "basic2d.nim");
	d = determinant_143438(t);
	nimln(463, "basic2d.nim");
	{
		Divbyzeroerror3441* e_143761;
		NimStringDesc* LOC5;
		if (!(d == 0.0)) goto LA3;
		e_143761 = 0;
		nimln(2265, "system.nim");
		e_143761 = (Divbyzeroerror3441*) newObj((&NTI23601), sizeof(Divbyzeroerror3441));
		(*e_143761).Sup.Sup.Sup.m_type = (&NTI3441);
		nimln(2266, "system.nim");
		LOC5 = 0;
		LOC5 = (*e_143761).Sup.Sup.message; (*e_143761).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP331));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(464, "basic2d.nim");
		raiseException((Exception*)e_143761, "DivByZeroError");
	}
	LA3: ;
	nimln(466, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)((*t).by) * (NF)((*v).x))) - (NF)(((NF)((*t).bx) * (NF)((*v).y))))) / (NF)(d));
	nimln(467, "basic2d.nim");
	(*v).y = ((NF)(((NF)(((NF)((*t).ax) * (NF)((*v).y))) - (NF)(((NF)((*t).ay) * (NF)((*v).x))))) / (NF)(d));
	nimln(468, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

N_NIMCALL(void, transformnorminv_143779)(Tvector2d143047* v, Tmatrix2d143043* t) {
	NF newx;
	nimfr("transformNormInv", "basic2d.nim")
	nimln(483, "basic2d.nim");
	newx = ((NF)(((NF)((*t).ay) * (NF)((*v).y))) + (NF)(((NF)((*t).ax) * (NF)((*v).x))));
	nimln(484, "basic2d.nim");
	(*v).y = ((NF)(((NF)((*t).by) * (NF)((*v).y))) + (NF)(((NF)((*t).bx) * (NF)((*v).x))));
	nimln(485, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

static N_INLINE(void, rotate90_143791)(Tvector2d143047* v) {
	NF LOC1;
	nimfr("rotate90", "basic2d.nim")
	nimln(490, "basic2d.nim");
	LOC1 = 0;
	LOC1 = (*v).x;
	(*v).x = (*v).y;
	(*v).y = LOC1;
	nimln(491, "basic2d.nim");
	(*v).x = -((*v).x);
	popFrame();
}

static N_INLINE(void, rotate180_143811)(Tvector2d143047* v) {
	nimfr("rotate180", "basic2d.nim")
	nimln(496, "basic2d.nim");
	(*v).x = -((*v).x);
	nimln(497, "basic2d.nim");
	(*v).y = -((*v).y);
	popFrame();
}

static N_INLINE(void, rotate270_143821)(Tvector2d143047* v) {
	NF LOC1;
	nimfr("rotate270", "basic2d.nim")
	nimln(502, "basic2d.nim");
	LOC1 = 0;
	LOC1 = (*v).x;
	(*v).x = (*v).y;
	(*v).y = LOC1;
	nimln(503, "basic2d.nim");
	(*v).y = -((*v).y);
	popFrame();
}

N_NIMCALL(void, rotate_143841)(Tvector2d143047* v, NF rad) {
	NF s;
	NF c;
	NF newx;
	nimfr("rotate", "basic2d.nim")
	nimln(508, "basic2d.nim");
	s = sin(rad);
	nimln(509, "basic2d.nim");
	c = cos(rad);
	nimln(510, "basic2d.nim");
	newx = ((NF)(((NF)(c) * (NF)((*v).x))) - (NF)(((NF)(s) * (NF)((*v).y))));
	nimln(511, "basic2d.nim");
	(*v).y = ((NF)(((NF)(c) * (NF)((*v).y))) + (NF)(((NF)(s) * (NF)((*v).x))));
	nimln(512, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

static N_INLINE(void, scale_143855)(Tvector2d143047* v, NF fac) {
	nimfr("scale", "basic2d.nim")
	nimln(516, "basic2d.nim");
	HEX2AHEX3D_143593((&(*v).x), fac);
	nimln(517, "basic2d.nim");
	HEX2AHEX3D_143593((&(*v).y), fac);
	popFrame();
}

static N_INLINE(void, stretch_143886)(Tvector2d143047* v, NF facx, NF facy) {
	nimfr("stretch", "basic2d.nim")
	nimln(522, "basic2d.nim");
	HEX2AHEX3D_143593((&(*v).x), facx);
	nimln(523, "basic2d.nim");
	HEX2AHEX3D_143593((&(*v).y), facy);
	popFrame();
}

N_NIMCALL(void, mirror_143918)(Tvector2d143047* v, Tvector2d143047 mirrvec) {
	NF sqx;
	NF sqy;
	NF nd;
	NF xy2;
	NF sqd;
	NF newx;
	nimfr("mirror", "basic2d.nim")
{	nimln(528, "basic2d.nim");
	sqx = ((NF)(mirrvec.x) * (NF)(mirrvec.x));
	nimln(529, "basic2d.nim");
	sqy = ((NF)(mirrvec.y) * (NF)(mirrvec.y));
	nimln(530, "basic2d.nim");
	nd = ((NF)(1.0000000000000000e+000) / (NF)(((NF)(sqx) + (NF)(sqy))));
	nimln(531, "basic2d.nim");
	xy2 = ((NF)(((NF)(((NF)(mirrvec.x) * (NF)(mirrvec.y))) * (NF)(2.0000000000000000e+000))) * (NF)(nd));
	nimln(532, "basic2d.nim");
	sqd = ((NF)(nd) * (NF)(((NF)(sqx) - (NF)(sqy))));
	nimln(534, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (nd == INF);
		if (LOC3) goto LA4;
		LOC3 = (nd == -INF);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(535, "basic2d.nim");
		goto BeforeRet;
	}
	LA5: ;
	nimln(537, "basic2d.nim");
	newx = ((NF)(((NF)(xy2) * (NF)((*v).y))) + (NF)(((NF)(sqd) * (NF)((*v).x))));
	nimln(538, "basic2d.nim");
	(*v).y = ((NF)(((NF)((*v).x) * (NF)(xy2))) - (NF)(((NF)(sqd) * (NF)((*v).y))));
	nimln(539, "basic2d.nim");
	(*v).x = newx;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(Tvector2d143047, HEX2D_143941)(Tvector2d143047 v) {
	Tvector2d143047 result;
	nimfr("-", "basic2d.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(544, "basic2d.nim");
	result.x = -(v.x);
	nimln(545, "basic2d.nim");
	result.y = -(v.y);
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2B_143963)(Tvector2d143047 a_143952, Tvector2d143047 b_143954) {
	Tvector2d143047 result;
	nimfr("+", "basic2d.nim")
	nimln(119, "basic2d.nim");
	result = vector2d_143072(((NF)(a_143952.x) + (NF)(b_143954.x)), ((NF)(a_143952.y) + (NF)(b_143954.y)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2B_143969)(Tvector2d143047 a_143956, NF b_143958) {
	Tvector2d143047 result;
	nimfr("+", "basic2d.nim")
	nimln(120, "basic2d.nim");
	result = vector2d_143072(((NF)(a_143956.x) + (NF)(b_143958)), ((NF)(a_143956.y) + (NF)(b_143958)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2B_143975)(NF a_143960, Tvector2d143047 b_143962) {
	Tvector2d143047 result;
	nimfr("+", "basic2d.nim")
	nimln(121, "basic2d.nim");
	result = vector2d_143072(((NF)(a_143960) + (NF)(b_143962.x)), ((NF)(a_143960) + (NF)(b_143962.y)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2D_143996)(Tvector2d143047 a_143985, Tvector2d143047 b_143987) {
	Tvector2d143047 result;
	nimfr("-", "basic2d.nim")
	nimln(119, "basic2d.nim");
	result = vector2d_143072(((NF)(a_143985.x) - (NF)(b_143987.x)), ((NF)(a_143985.y) - (NF)(b_143987.y)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2D_144002)(Tvector2d143047 a_143989, NF b_143991) {
	Tvector2d143047 result;
	nimfr("-", "basic2d.nim")
	nimln(120, "basic2d.nim");
	result = vector2d_143072(((NF)(a_143989.x) - (NF)(b_143991)), ((NF)(a_143989.y) - (NF)(b_143991)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2D_144008)(NF a_143993, Tvector2d143047 b_143995) {
	Tvector2d143047 result;
	nimfr("-", "basic2d.nim")
	nimln(121, "basic2d.nim");
	result = vector2d_143072(((NF)(a_143993) - (NF)(b_143995.x)), ((NF)(a_143993) - (NF)(b_143995.y)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2A_144029)(Tvector2d143047 a_144018, Tvector2d143047 b_144020) {
	Tvector2d143047 result;
	nimfr("*", "basic2d.nim")
	nimln(119, "basic2d.nim");
	result = vector2d_143072(((NF)(a_144018.x) * (NF)(b_144020.x)), ((NF)(a_144018.y) * (NF)(b_144020.y)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2A_144035)(Tvector2d143047 a_144022, NF b_144024) {
	Tvector2d143047 result;
	nimfr("*", "basic2d.nim")
	nimln(120, "basic2d.nim");
	result = vector2d_143072(((NF)(a_144022.x) * (NF)(b_144024)), ((NF)(a_144022.y) * (NF)(b_144024)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2A_144041)(NF a_144026, Tvector2d143047 b_144028) {
	Tvector2d143047 result;
	nimfr("*", "basic2d.nim")
	nimln(121, "basic2d.nim");
	result = vector2d_143072(((NF)(a_144026) * (NF)(b_144028.x)), ((NF)(a_144026) * (NF)(b_144028.y)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2F_144062)(Tvector2d143047 a_144051, Tvector2d143047 b_144053) {
	Tvector2d143047 result;
	nimfr("/", "basic2d.nim")
	nimln(119, "basic2d.nim");
	result = vector2d_143072(((NF)(a_144051.x) / (NF)(b_144053.x)), ((NF)(a_144051.y) / (NF)(b_144053.y)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2F_144068)(Tvector2d143047 a_144055, NF b_144057) {
	Tvector2d143047 result;
	nimfr("/", "basic2d.nim")
	nimln(120, "basic2d.nim");
	result = vector2d_143072(((NF)(a_144055.x) / (NF)(b_144057)), ((NF)(a_144055.y) / (NF)(b_144057)));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2F_144074)(NF a_144059, Tvector2d143047 b_144061) {
	Tvector2d143047 result;
	nimfr("/", "basic2d.nim")
	nimln(121, "basic2d.nim");
	result = vector2d_143072(((NF)(a_144059) / (NF)(b_144061.x)), ((NF)(a_144059) / (NF)(b_144061.y)));
	popFrame();
	return result;
}

static N_INLINE(void, HEX2BHEX3D_144091)(Tvector2d143047* a_144084, Tvector2d143047 b_144086) {
	nimfr("+=", "basic2d.nim")
	nimln(125, "basic2d.nim");
	HEX2BHEX3D_107689((&(*a_144084).x), b_144086.x);
	HEX2BHEX3D_107689((&(*a_144084).y), b_144086.y);
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_144117)(Tvector2d143047* a_144088, NF b_144090) {
	nimfr("+=", "basic2d.nim")
	nimln(126, "basic2d.nim");
	HEX2BHEX3D_107689((&(*a_144088).x), b_144090);
	HEX2BHEX3D_107689((&(*a_144088).y), b_144090);
	popFrame();
}

static N_INLINE(void, HEX2DHEX3D_144158)(NF* x, NF y) {
	nimfr("-=", "system.nim")
	nimln(2996, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

static N_INLINE(void, HEX2DHEX3D_144154)(Tvector2d143047* a_144147, Tvector2d143047 b_144149) {
	nimfr("-=", "basic2d.nim")
	nimln(125, "basic2d.nim");
	HEX2DHEX3D_144158((&(*a_144147).x), b_144149.x);
	HEX2DHEX3D_144158((&(*a_144147).y), b_144149.y);
	popFrame();
}

static N_INLINE(void, HEX2DHEX3D_144183)(Tvector2d143047* a_144151, NF b_144153) {
	nimfr("-=", "basic2d.nim")
	nimln(126, "basic2d.nim");
	HEX2DHEX3D_144158((&(*a_144151).x), b_144153);
	HEX2DHEX3D_144158((&(*a_144151).y), b_144153);
	popFrame();
}

static N_INLINE(void, HEX2AHEX3D_144220)(Tvector2d143047* a_144213, Tvector2d143047 b_144215) {
	nimfr("*=", "basic2d.nim")
	nimln(125, "basic2d.nim");
	HEX2AHEX3D_143593((&(*a_144213).x), b_144215.x);
	HEX2AHEX3D_143593((&(*a_144213).y), b_144215.y);
	popFrame();
}

static N_INLINE(void, HEX2AHEX3D_144246)(Tvector2d143047* a_144217, NF b_144219) {
	nimfr("*=", "basic2d.nim")
	nimln(126, "basic2d.nim");
	HEX2AHEX3D_143593((&(*a_144217).x), b_144219);
	HEX2AHEX3D_143593((&(*a_144217).y), b_144219);
	popFrame();
}

static N_INLINE(void, HEX2FHEX3D_144283)(Tvector2d143047* a_144276, Tvector2d143047 b_144278) {
	nimfr("/=", "basic2d.nim")
	nimln(125, "basic2d.nim");
	HEX2FHEX3D_88702((&(*a_144276).x), b_144278.x);
	HEX2FHEX3D_88702((&(*a_144276).y), b_144278.y);
	popFrame();
}

static N_INLINE(void, HEX2FHEX3D_144291)(Tvector2d143047* a_144280, NF b_144282) {
	nimfr("/=", "basic2d.nim")
	nimln(126, "basic2d.nim");
	HEX2FHEX3D_88702((&(*a_144280).x), b_144282);
	HEX2FHEX3D_88702((&(*a_144280).y), b_144282);
	popFrame();
}

N_NIMCALL(NF, dot_144302)(Tvector2d143047 v1, Tvector2d143047 v2) {
	NF result;
	nimfr("dot", "basic2d.nim")
{	result = 0;
	nimln(561, "basic2d.nim");
	result = ((NF)(((NF)(v1.x) * (NF)(v2.x))) + (NF)(((NF)(v1.y) * (NF)(v2.y))));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, cross_144313)(Tvector2d143047 v1, Tvector2d143047 v2) {
	NF result;
	nimfr("cross", "basic2d.nim")
{	result = 0;
	nimln(567, "basic2d.nim");
	result = ((NF)(((NF)(v1.x) * (NF)(v2.y))) - (NF)(((NF)(v1.y) * (NF)(v2.x))));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, equals_144324)(Tvector2d143047 v1, Tvector2d143047 v2, NF tol) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("equals", "basic2d.nim")
{	result = 0;
	nimln(571, "basic2d.nim");
	LOC1 = 0;
	LOC1 = ((((NF)(v2.x) - (NF)(v1.x)) > 0? (((NF)(v2.x) - (NF)(v1.x))) : -(((NF)(v2.x) - (NF)(v1.x)))) <= tol);
	if (!(LOC1)) goto LA2;
	LOC1 = ((((NF)(v2.y) - (NF)(v1.y)) > 0? (((NF)(v2.y) - (NF)(v1.y))) : -(((NF)(v2.y) - (NF)(v1.y)))) <= tol);
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX7E_144337)(Tvector2d143047 v1, Tvector2d143047 v2) {
	NIM_BOOL result;
	nimfr("=~", "basic2d.nim")
	result = 0;
	nimln(574, "basic2d.nim");
	nimln(576, "basic2d.nim");
	result = equals_144324(v1, v2, 9.9999999999999995e-007);
	popFrame();
	return result;
}

N_NIMCALL(NF, angleto_144348)(Tvector2d143047 v1, Tvector2d143047 v2) {
	NF result;
	Tvector2d143047 nv1;
	Tvector2d143047 nv2;
	NF LOC9;
	nimfr("angleTo", "basic2d.nim")
{	result = 0;
	nimln(582, "basic2d.nim");
	nv1 = v1;
	nimln(583, "basic2d.nim");
	nv2 = v2;
	nimln(584, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC6;
		LOC3 = 0;
		LOC4 = 0;
		LOC4 = trynormalize_143687((&nv1));
		LOC3 = !(LOC4);
		if (LOC3) goto LA5;
		LOC6 = 0;
		LOC6 = trynormalize_143687((&nv2));
		LOC3 = !(LOC6);
		LA5: ;
		if (!LOC3) goto LA7;
		nimln(585, "basic2d.nim");
		result = 0.0;
		goto BeforeRet;
	}
	LA7: ;
	nimln(586, "basic2d.nim");
	LOC9 = 0;
	LOC9 = dot_144302(nv1, nv2);
	result = safearccos_143128(LOC9);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, angleccw_144364)(Tvector2d143047 v1, Tvector2d143047 v2) {
	NF result;
	NF a;
	nimfr("angleCCW", "basic2d.nim")
{	result = 0;
	nimln(591, "basic2d.nim");
	a = angleto_144348(v1, v2);
	nimln(592, "basic2d.nim");
	{
		NF LOC3;
		LOC3 = 0;
		LOC3 = cross_144313(v1, v2);
		if (!(0.0 <= LOC3)) goto LA4;
		nimln(593, "basic2d.nim");
		result = a;
		goto BeforeRet;
	}
	LA4: ;
	nimln(594, "basic2d.nim");
	result = ((NF)(6.2831853071795862e+000) - (NF)(a));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, anglecw_144377)(Tvector2d143047 v1, Tvector2d143047 v2) {
	NF result;
	NF a;
	nimfr("angleCW", "basic2d.nim")
{	result = 0;
	nimln(599, "basic2d.nim");
	a = angleto_144348(v1, v2);
	nimln(600, "basic2d.nim");
	{
		NF LOC3;
		LOC3 = 0;
		LOC3 = cross_144313(v1, v2);
		if (!(LOC3 <= 0.0)) goto LA4;
		nimln(601, "basic2d.nim");
		result = a;
		goto BeforeRet;
	}
	LA4: ;
	nimln(602, "basic2d.nim");
	result = ((NF)(6.2831853071795862e+000) - (NF)(a));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, turnangle_144390)(Tvector2d143047 v1, Tvector2d143047 v2) {
	NF result;
	NF a;
	nimfr("turnAngle", "basic2d.nim")
{	result = 0;
	nimln(607, "basic2d.nim");
	a = angleto_144348(v1, v2);
	nimln(608, "basic2d.nim");
	{
		NF LOC3;
		LOC3 = 0;
		LOC3 = cross_144313(v1, v2);
		if (!(LOC3 <= 0.0)) goto LA4;
		nimln(609, "basic2d.nim");
		result = -(a);
		goto BeforeRet;
	}
	LA4: ;
	nimln(610, "basic2d.nim");
	result = a;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Tvector2d143047, bisect_144403)(Tvector2d143047 v1, Tvector2d143047 v2) {
	Tvector2d143047 result;
	NF vmag1;
	NF vmag2;
	NF x1;
	NF y1;
	NF x2;
	NF y2;
	nimfr("bisect", "basic2d.nim")
{	nimln(618, "basic2d.nim");
	vmag1 = len_143570(v1);
	nimln(619, "basic2d.nim");
	vmag2 = len_143570(v2);
	nimln(623, "basic2d.nim");
	{
		if (!(vmag1 == 0.0)) goto LA3;
		nimln(624, "basic2d.nim");
		{
			if (!(vmag2 == 0.0)) goto LA7;
			nimln(625, "basic2d.nim");
			result = Xaxis_143098;
			goto BeforeRet;
		}
		LA7: ;
		nimln(626, "basic2d.nim");
		vmag1 = 1.0000000000000000e+000;
	}
	LA3: ;
	nimln(627, "basic2d.nim");
	{
		if (!(vmag2 == 0.0)) goto LA11;
		vmag2 = 1.0000000000000000e+000;
	}
	LA11: ;
	nimln(630, "basic2d.nim");
	x1 = ((NF)(v1.x) / (NF)(vmag1));
	nimln(631, "basic2d.nim");
	y1 = ((NF)(v1.y) / (NF)(vmag1));
	nimln(632, "basic2d.nim");
	x2 = ((NF)(v2.x) / (NF)(vmag2));
	nimln(633, "basic2d.nim");
	y2 = ((NF)(v2.y) / (NF)(vmag2));
	nimln(635, "basic2d.nim");
	result.x = ((NF)(((NF)(x1) + (NF)(x2))) * (NF)(5.0000000000000000e-001));
	nimln(636, "basic2d.nim");
	result.y = ((NF)(((NF)(y1) + (NF)(y2))) * (NF)(5.0000000000000000e-001));
	nimln(638, "basic2d.nim");
	{
		NIM_BOOL LOC15;
		LOC15 = 0;
		LOC15 = trynormalize_143687((&result));
		if (!!(LOC15)) goto LA16;
		nimln(642, "basic2d.nim");
		result.x = -(y1);
		nimln(643, "basic2d.nim");
		result.y = x1;
	}
	LA16: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(Tpoint2d143045, point2d_143079)(NF x, NF y) {
	Tpoint2d143045 result;
	nimfr("point2d", "basic2d.nim")
	nimln(652, "basic2d.nim");
	result.x = x;
	nimln(653, "basic2d.nim");
	result.y = y;
	popFrame();
	return result;
}

N_NIMCALL(NF, sqrdist_144440)(Tpoint2d143045 a, Tpoint2d143045 b) {
	NF result;
	NF dx;
	NF dy;
	nimfr("sqrDist", "basic2d.nim")
	result = 0;
	nimln(657, "basic2d.nim");
	dx = ((NF)(b.x) - (NF)(a.x));
	nimln(658, "basic2d.nim");
	dy = ((NF)(b.y) - (NF)(a.y));
	nimln(659, "basic2d.nim");
	result = ((NF)(((NF)(dx) * (NF)(dx))) + (NF)(((NF)(dy) * (NF)(dy))));
	popFrame();
	return result;
}

static N_INLINE(NF, dist_144453)(Tpoint2d143045 a, Tpoint2d143045 b) {
	NF result;
	NF LOC1;
	nimfr("dist", "basic2d.nim")
	result = 0;
	nimln(663, "basic2d.nim");
	LOC1 = 0;
	LOC1 = sqrdist_144440(a, b);
	result = sqrt(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NF, angle_144464)(Tpoint2d143045 a, Tpoint2d143045 b) {
	NF result;
	NF dx;
	NF dy;
	nimfr("angle", "basic2d.nim")
	result = 0;
	nimln(667, "basic2d.nim");
	dx = ((NF)(b.x) - (NF)(a.x));
	nimln(668, "basic2d.nim");
	dy = ((NF)(b.y) - (NF)(a.y));
	nimln(669, "basic2d.nim");
	result = atan2(dy, dx);
	nimln(670, "basic2d.nim");
	{
		if (!(result < 0.0)) goto LA3;
		nimln(671, "basic2d.nim");
		HEX2BHEX3D_107689((&result), 6.2831853071795862e+000);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_144489)(Tpoint2d143045 p) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	nimfr("$", "basic2d.nim")
	result = 0;
	nimln(675, "basic2d.nim");
	result = rtos_143118(p.x);
	nimln(676, "basic2d.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP328));
	nimln(677, "basic2d.nim");
	LOC1 = 0;
	LOC1 = rtos_143118(p.y);
	result = resizeString(result, LOC1->Sup.len + 0);
appendString(result, LOC1);
	popFrame();
	return result;
}

static N_INLINE(Tpoint2d143045, HEX26_144499)(Tpoint2d143045 p, Tmatrix2d143043* t) {
	Tpoint2d143045 result;
	nimfr("&", "basic2d.nim")
	nimln(686, "basic2d.nim");
	result.x = ((NF)(((NF)(((NF)(p.x) * (NF)((*t).ax))) + (NF)(((NF)(p.y) * (NF)((*t).bx))))) + (NF)((*t).tx));
	nimln(687, "basic2d.nim");
	result.y = ((NF)(((NF)(((NF)(p.x) * (NF)((*t).ay))) + (NF)(((NF)(p.y) * (NF)((*t).by))))) + (NF)((*t).ty));
	popFrame();
	return result;
}

static N_INLINE(void, HEX26HEX3D_144510)(Tpoint2d143045* p, Tmatrix2d143043* t) {
	NF newx;
	nimfr("&=", "basic2d.nim")
	nimln(691, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)((*p).x) * (NF)((*t).ax))) + (NF)(((NF)((*p).y) * (NF)((*t).bx))))) + (NF)((*t).tx));
	nimln(692, "basic2d.nim");
	(*p).y = ((NF)(((NF)(((NF)((*p).x) * (NF)((*t).ay))) + (NF)(((NF)((*p).y) * (NF)((*t).by))))) + (NF)((*t).ty));
	nimln(693, "basic2d.nim");
	(*p).x = newx;
	popFrame();
}

static N_INLINE(void, transforminv_144522)(Tpoint2d143045* p, Tmatrix2d143043* t) {
	NF d;
	NF newx;
	nimfr("transformInv", "basic2d.nim")
	nimln(704, "basic2d.nim");
	d = determinant_143438(t);
	nimln(705, "basic2d.nim");
	{
		Divbyzeroerror3441* e_144531;
		NimStringDesc* LOC5;
		if (!(d == 0.0)) goto LA3;
		e_144531 = 0;
		nimln(2265, "system.nim");
		e_144531 = (Divbyzeroerror3441*) newObj((&NTI23601), sizeof(Divbyzeroerror3441));
		(*e_144531).Sup.Sup.Sup.m_type = (&NTI3441);
		nimln(2266, "system.nim");
		LOC5 = 0;
		LOC5 = (*e_144531).Sup.Sup.message; (*e_144531).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP329));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(706, "basic2d.nim");
		raiseException((Exception*)e_144531, "DivByZeroError");
	}
	LA3: ;
	nimln(708, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)(((NF)(((NF)((*t).bx) * (NF)((*t).ty))) - (NF)(((NF)((*t).by) * (NF)((*t).tx))))) + (NF)(((NF)((*p).x) * (NF)((*t).by))))) - (NF)(((NF)((*p).y) * (NF)((*t).bx))))) / (NF)(d));
	nimln(709, "basic2d.nim");
	(*p).y = ((NF)(-(((NF)(((NF)(((NF)(((NF)((*t).ax) * (NF)((*t).ty))) - (NF)(((NF)((*t).ay) * (NF)((*t).tx))))) + (NF)(((NF)((*p).x) * (NF)((*t).ay))))) - (NF)(((NF)((*p).y) * (NF)((*t).ax)))))) / (NF)(d));
	nimln(710, "basic2d.nim");
	(*p).x = newx;
	popFrame();
}

static N_INLINE(Tpoint2d143045, HEX2B_144549)(Tpoint2d143045 p, Tvector2d143047 v) {
	Tpoint2d143045 result;
	nimfr("+", "basic2d.nim")
	nimln(716, "basic2d.nim");
	result.x = ((NF)(p.x) + (NF)(v.x));
	nimln(717, "basic2d.nim");
	result.y = ((NF)(p.y) + (NF)(v.y));
	popFrame();
	return result;
}

static N_INLINE(void, HEX2BHEX3D_144560)(Tpoint2d143045* p, Tvector2d143047 v) {
	nimfr("+=", "basic2d.nim")
	nimln(721, "basic2d.nim");
	HEX2BHEX3D_107689((&(*p).x), v.x);
	nimln(722, "basic2d.nim");
	HEX2BHEX3D_107689((&(*p).y), v.y);
	popFrame();
}

static N_INLINE(Tpoint2d143045, HEX2D_144591)(Tpoint2d143045 p, Tvector2d143047 v) {
	Tpoint2d143045 result;
	nimfr("-", "basic2d.nim")
	nimln(727, "basic2d.nim");
	result.x = ((NF)(p.x) - (NF)(v.x));
	nimln(728, "basic2d.nim");
	result.y = ((NF)(p.y) - (NF)(v.y));
	popFrame();
	return result;
}

static N_INLINE(Tvector2d143047, HEX2D_144602)(Tpoint2d143045 p1, Tpoint2d143045 p2) {
	Tvector2d143047 result;
	nimfr("-", "basic2d.nim")
	nimln(732, "basic2d.nim");
	result.x = ((NF)(p1.x) - (NF)(p2.x));
	nimln(733, "basic2d.nim");
	result.y = ((NF)(p1.y) - (NF)(p2.y));
	popFrame();
	return result;
}

static N_INLINE(void, HEX2DHEX3D_144613)(Tpoint2d143045* p, Tvector2d143047 v) {
	nimfr("-=", "basic2d.nim")
	nimln(737, "basic2d.nim");
	HEX2DHEX3D_144158((&(*p).x), v.x);
	nimln(738, "basic2d.nim");
	HEX2DHEX3D_144158((&(*p).y), v.y);
	popFrame();
}

static N_INLINE(NIM_BOOL, equals_144644)(Tpoint2d143045 p1, Tpoint2d143045 p2, NF tol) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("equals", "basic2d.nim")
{	result = 0;
	nimln(742, "basic2d.nim");
	LOC1 = 0;
	LOC1 = ((((NF)(p2.x) - (NF)(p1.x)) > 0? (((NF)(p2.x) - (NF)(p1.x))) : -(((NF)(p2.x) - (NF)(p1.x)))) <= tol);
	if (!(LOC1)) goto LA2;
	LOC1 = ((((NF)(p2.y) - (NF)(p1.y)) > 0? (((NF)(p2.y) - (NF)(p1.y))) : -(((NF)(p2.y) - (NF)(p1.y)))) <= tol);
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, HEX3DHEX7E_144657)(Tpoint2d143045 p1, Tpoint2d143045 p2) {
	NIM_BOOL result;
	nimfr("=~", "basic2d.nim")
	result = 0;
	nimln(745, "basic2d.nim");
	nimln(747, "basic2d.nim");
	result = equals_144644(p1, p2, 9.9999999999999995e-007);
	popFrame();
	return result;
}

N_NIMCALL(Tpoint2d143045, polar_144668)(Tpoint2d143045 p, NF ang, NF dist) {
	Tpoint2d143045 result;
	NF LOC1;
	NF LOC2;
	nimfr("polar", "basic2d.nim")
	nimln(751, "basic2d.nim");
	LOC1 = 0;
	LOC1 = cos(ang);
	result.x = ((NF)(p.x) + (NF)(((NF)(LOC1) * (NF)(dist))));
	nimln(752, "basic2d.nim");
	LOC2 = 0;
	LOC2 = sin(ang);
	result.y = ((NF)(p.y) + (NF)(((NF)(LOC2) * (NF)(dist))));
	popFrame();
	return result;
}

N_NIMCALL(void, rotate_144680)(Tpoint2d143045* p, NF rad) {
	NF c;
	NF s;
	NF newx;
	nimfr("rotate", "basic2d.nim")
	nimln(757, "basic2d.nim");
	c = cos(rad);
	nimln(758, "basic2d.nim");
	s = sin(rad);
	nimln(759, "basic2d.nim");
	newx = ((NF)(((NF)((*p).x) * (NF)(c))) - (NF)(((NF)((*p).y) * (NF)(s))));
	nimln(760, "basic2d.nim");
	(*p).y = ((NF)(((NF)((*p).y) * (NF)(c))) + (NF)(((NF)((*p).x) * (NF)(s))));
	nimln(761, "basic2d.nim");
	(*p).x = newx;
	popFrame();
}

N_NIMCALL(void, rotate_144694)(Tpoint2d143045* p, NF rad, Tpoint2d143045 org) {
	NF c;
	NF s;
	NF newx;
	nimfr("rotate", "basic2d.nim")
	nimln(767, "basic2d.nim");
	c = cos(rad);
	nimln(768, "basic2d.nim");
	s = sin(rad);
	nimln(769, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)(((NF)((*p).x) - (NF)(org.x))) * (NF)(c))) - (NF)(((NF)(((NF)((*p).y) - (NF)(org.y))) * (NF)(s))))) + (NF)(org.x));
	nimln(770, "basic2d.nim");
	(*p).y = ((NF)(((NF)(((NF)(((NF)((*p).y) - (NF)(org.y))) * (NF)(c))) + (NF)(((NF)(((NF)((*p).x) - (NF)(org.x))) * (NF)(s))))) + (NF)(org.y));
	nimln(771, "basic2d.nim");
	(*p).x = newx;
	popFrame();
}

static N_INLINE(void, scale_144709)(Tpoint2d143045* p, NF fac) {
	nimfr("scale", "basic2d.nim")
	nimln(775, "basic2d.nim");
	HEX2AHEX3D_143593((&(*p).x), fac);
	nimln(776, "basic2d.nim");
	HEX2AHEX3D_143593((&(*p).y), fac);
	popFrame();
}

static N_INLINE(void, scale_144740)(Tpoint2d143045* p, NF fac, Tpoint2d143045 org) {
	nimfr("scale", "basic2d.nim")
	nimln(780, "basic2d.nim");
	(*p).x = ((NF)(((NF)(((NF)((*p).x) - (NF)(org.x))) * (NF)(fac))) + (NF)(org.x));
	nimln(781, "basic2d.nim");
	(*p).y = ((NF)(((NF)(((NF)((*p).y) - (NF)(org.y))) * (NF)(fac))) + (NF)(org.y));
	popFrame();
}

static N_INLINE(void, stretch_144752)(Tpoint2d143045* p, NF facx, NF facy) {
	nimfr("stretch", "basic2d.nim")
	nimln(786, "basic2d.nim");
	HEX2AHEX3D_143593((&(*p).x), facx);
	nimln(787, "basic2d.nim");
	HEX2AHEX3D_143593((&(*p).y), facy);
	popFrame();
}

static N_INLINE(void, stretch_144784)(Tpoint2d143045* p, NF facx, NF facy, Tpoint2d143045 org) {
	nimfr("stretch", "basic2d.nim")
	nimln(792, "basic2d.nim");
	(*p).x = ((NF)(((NF)(((NF)((*p).x) - (NF)(org.x))) * (NF)(facx))) + (NF)(org.x));
	nimln(793, "basic2d.nim");
	(*p).y = ((NF)(((NF)(((NF)((*p).y) - (NF)(org.y))) * (NF)(facy))) + (NF)(org.y));
	popFrame();
}

static N_INLINE(void, move_144797)(Tpoint2d143045* p, NF dx, NF dy) {
	nimfr("move", "basic2d.nim")
	nimln(797, "basic2d.nim");
	HEX2BHEX3D_107689((&(*p).x), dx);
	nimln(798, "basic2d.nim");
	HEX2BHEX3D_107689((&(*p).y), dy);
	popFrame();
}

static N_INLINE(void, move_144829)(Tpoint2d143045* p, Tvector2d143047 v) {
	nimfr("move", "basic2d.nim")
	nimln(802, "basic2d.nim");
	HEX2BHEX3D_107689((&(*p).x), v.x);
	nimln(803, "basic2d.nim");
	HEX2BHEX3D_107689((&(*p).y), v.y);
	popFrame();
}

N_NIMCALL(NF, sgnarea_144860)(Tpoint2d143045 a, Tpoint2d143045 b, Tpoint2d143045 c) {
	NF result;
	nimfr("sgnArea", "basic2d.nim")
{	result = 0;
	nimln(810, "basic2d.nim");
	result = ((NF)(((NF)(((NF)(((NF)(b.x) - (NF)(c.x))) * (NF)(((NF)(b.y) - (NF)(a.y))))) - (NF)(((NF)(((NF)(b.y) - (NF)(c.y))) * (NF)(((NF)(b.x) - (NF)(a.x))))))) * (NF)(5.0000000000000000e-001));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, area_144873)(Tpoint2d143045 a, Tpoint2d143045 b, Tpoint2d143045 c) {
	NF result;
	NF LOC1;
	nimfr("area", "basic2d.nim")
{	result = 0;
	nimln(814, "basic2d.nim");
	LOC1 = 0;
	LOC1 = sgnarea_144860(a, b, c);
	result = (LOC1 > 0? (LOC1) : -(LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Tpoint2d143045, closestpoint_144885)(Tpoint2d143045 p, Tpoint2d143045* pts, NI ptsLen0) {
	Tpoint2d143045 result;
	NI bestidx;
	NF bestdist;
	NF curdist;
	nimfr("closestPoint", "basic2d.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(819, "basic2d.nim");
	{
		if (!!((((NI) 0) < ptsLen0))) goto LA3;
		failedassertimpl_88817(((NimStringDesc*) &TMP332));
	}
	LA3: ;
	nimln(822, "basic2d.nim");
	bestidx = ((NI) 0);
	nimln(823, "basic2d.nim");
	if ((NU)(((NI) 0)) >= (NU)(ptsLen0)) raiseIndexError();
	bestdist = sqrdist_144440(p, pts[((NI) 0)]);
	curdist = 0;
	{
		NI idx_145014;
		NI HEX3Atmp_145017;
		NI res_145020;
		idx_145014 = 0;
		HEX3Atmp_145017 = 0;
		nimln(826, "basic2d.nim");
		HEX3Atmp_145017 = (ptsLen0-1);
		nimln(1598, "system.nim");
		res_145020 = ((NI) 1);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP333;
				if (!(res_145020 <= HEX3Atmp_145017)) goto LA7;
				nimln(1600, "system.nim");
				idx_145014 = res_145020;
				nimln(827, "basic2d.nim");
				if ((NU)(idx_145014) >= (NU)(ptsLen0)) raiseIndexError();
				curdist = sqrdist_144440(p, pts[idx_145014]);
				nimln(828, "basic2d.nim");
				{
					if (!(curdist < bestdist)) goto LA10;
					nimln(829, "basic2d.nim");
					bestidx = idx_145014;
					nimln(830, "basic2d.nim");
					bestdist = curdist;
				}
				LA10: ;
				nimln(1619, "system.nim");
				TMP333 = addInt(res_145020, ((NI) 1));
				res_145020 = (NI)(TMP333);
			} LA7: ;
		}
	}
	nimln(832, "basic2d.nim");
	if ((NU)(bestidx) >= (NU)(ptsLen0)) raiseIndexError();
	result = pts[bestidx];
	popFrame();
	return result;
}

N_NIMCALL(NF, normangle_145039)(NF ang) {
	NF result;
	nimfr("normAngle", "basic2d.nim")
{	result = 0;
	nimln(842, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0.0 <= ang);
		if (!(LOC3)) goto LA4;
		LOC3 = (ang < 6.2831853071795862e+000);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(843, "basic2d.nim");
		result = ang;
		goto BeforeRet;
	}
	LA5: ;
	nimln(845, "basic2d.nim");
	result = mod_112807(ang, 6.2831853071795862e+000);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NF, degtorad_145050)(NF deg) {
	NF result;
	nimfr("degToRad", "basic2d.nim")
	result = 0;
	nimln(848, "basic2d.nim");
	nimln(849, "basic2d.nim");
	result = ((NF)(deg) / (NF)(5.7295779513082323e+001));
	popFrame();
	return result;
}

static N_INLINE(NF, radtodeg_145060)(NF rad) {
	NF result;
	nimfr("radToDeg", "basic2d.nim")
	result = 0;
	nimln(852, "basic2d.nim");
	nimln(853, "basic2d.nim");
	result = ((NF)(rad) * (NF)(5.7295779513082323e+001));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit)(void) {
	nimfr("basic2d", "basic2d.nim")
	nimln(93, "basic2d.nim");
	Idmatrix_143092 = matrix2d_143061(1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000, 0.0, 0.0);
	nimln(95, "basic2d.nim");
	Origo_143095 = point2d_143079(0.0, 0.0);
	nimln(97, "basic2d.nim");
	Xaxis_143098 = vector2d_143072(1.0000000000000000e+000, 0.0);
	nimln(99, "basic2d.nim");
	Yaxis_143101 = vector2d_143072(0.0, 1.0000000000000000e+000);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit)(void) {
static TNimNode* TMP352[2];
static TNimNode TMP326[3];
NTI143047.size = sizeof(Tvector2d143047);
NTI143047.kind = 18;
NTI143047.base = 0;
NTI143047.flags = 3;
TMP352[0] = &TMP326[1];
TMP326[1].kind = 1;
TMP326[1].offset = offsetof(Tvector2d143047, x);
TMP326[1].typ = (&NTI128);
TMP326[1].name = "x";
TMP352[1] = &TMP326[2];
TMP326[2].kind = 1;
TMP326[2].offset = offsetof(Tvector2d143047, y);
TMP326[2].typ = (&NTI128);
TMP326[2].name = "y";
TMP326[0].len = 2; TMP326[0].kind = 2; TMP326[0].sons = &TMP352[0];
NTI143047.node = &TMP326[0];
}

